// @ts-checked-v5.8
// ============================================================
// GENESIS — SessionPersistence.js (v3.5.0 — REVOLUTION)
//
// PROBLEM: Genesis loses almost everything between restarts.
// It knows the user's name (semantic memory) and has a journal,
// but it doesn't know:
// - What it was working on
// - What the user's project is about
// - What decisions were made
// - What it learned in the last session
//
// SOLUTION: At shutdown, Genesis creates a SESSION SUMMARY —
// a compressed narrative of what happened, generated by the LLM.
// At boot, this summary is loaded into the system prompt,
// giving Genesis immediate awareness of its recent history.
//
// Additionally, it maintains a USER PROFILE that accumulates
// across sessions: interests, preferences, project context,
// communication style, language.
//
// Architecture:
//   Shutdown → LLM summarizes session → saved to disk
//   Boot → summary loaded → injected into PromptBuilder
//   Continuous → user profile updated from conversation patterns
// ============================================================

const { NullBus } = require('../core/EventBus');
const { createLogger } = require('../core/Logger');
const { TIMEOUTS } = require('../core/Constants');
const _log = createLogger('SessionPersistence');

class SessionPersistence {
  static containerConfig = {
    name: 'sessionPersistence',
    phase: 7,
    deps: ['model', 'memory', 'storage'],
    tags: ['revolution', 'memory'],
    lateBindings: [
      { target: 'promptBuilder', property: 'sessionPersistence' },
    ],
  };

  constructor({ bus, model, memory, storage, lang }) {
    this.bus = bus || NullBus;
    this.model = model;
    this.memory = memory;
    this.storage = storage || null;
    this.lang = lang || { t: k => k };

    // ── Session State ────────────────────────────────────
    this.currentSession = {
      startedAt: new Date().toISOString(),
      messageCount: 0,
      topicsDiscussed: [],
      errorsEncountered: [],
      goalsWorkedOn: [],
      keyDecisions: [],
      codeFilesModified: [],
    };

    // ── Persistent Across Sessions ───────────────────────
    this.sessionHistory = [];      // Last N session summaries
    this.maxSessionHistory = 10;
    this.userProfile = {
      name: null,
      language: null,
      interests: [],
      projects: [],
      preferences: {},
      communicationStyle: null,
      expertise: [],
      lastSeen: null,
    };

    // v3.8.0: Moved to asyncLoad() — called by Container.bootAll()
    // this._load();
    /** @type {Array<Function>} */
    this._unsubs = [];
    this._wireEvents();
  }

  // ════════════════════════════════════════════════════════
  // PUBLIC API
  // ════════════════════════════════════════════════════════

  /**
   * Build a boot context for PromptBuilder.
   * Injected into the system prompt at startup so Genesis
   * immediately knows what happened in previous sessions.
   */
  buildBootContext() {
    const parts = [];

    // User profile
    if (this.userProfile.name) {
      parts.push(`USER: ${this.userProfile.name}`);
    }
    if (this.userProfile.language) {
      parts.push(`PREFERRED LANGUAGE: ${this.userProfile.language}`);
    }
    if (this.userProfile.projects.length > 0) {
      parts.push(`USER'S PROJECTS: ${this.userProfile.projects.slice(-3).join(', ')}`);
    }
    if (this.userProfile.expertise.length > 0) {
      parts.push(`USER EXPERTISE: ${this.userProfile.expertise.slice(-5).join(', ')}`);
    }

    // Last session summary
    if (this.sessionHistory.length > 0) {
      const last = this.sessionHistory[this.sessionHistory.length - 1];
      parts.push('');
      parts.push('LAST SESSION SUMMARY:');
      parts.push(last.summary || 'No summary available');
      if (last.unfinishedWork) {
        parts.push(`UNFINISHED WORK: ${last.unfinishedWork}`);
      }
    }

    // Session before last (for longer context)
    if (this.sessionHistory.length > 1) {
      const prev = this.sessionHistory[this.sessionHistory.length - 2];
      if (prev.summary) {
        parts.push('');
        parts.push(`EARLIER SESSION: ${prev.summary.slice(0, 200)}`);
      }
    }

    return parts.length > 0 ? parts.join('\n') : '';
  }

  /**
   * Generate session summary using the LLM.
   * Called during shutdown (before the model goes offline).
   */
  async generateSessionSummary(chatHistory = []) {
    if (this.currentSession.messageCount === 0 && chatHistory.length === 0) {
      return null;
    }

    // Build a compact session overview
    const sessionData = {
      duration: this._getSessionDuration(),
      messages: this.currentSession.messageCount,
      topics: this.currentSession.topicsDiscussed.slice(-10),
      errors: this.currentSession.errorsEncountered.slice(-5),
      goals: this.currentSession.goalsWorkedOn,
      modifications: this.currentSession.codeFilesModified,
      decisions: this.currentSession.keyDecisions.slice(-5),
    };

    // Get last few messages for context
    const recentMessages = chatHistory.slice(-10).map(m =>
      `${m.role}: ${m.content.slice(0, 150)}`
    ).join('\n');

    try {
      const prompt = `You are Genesis. Your current session is ending. Create a brief summary for yourself to read when you restart.

SESSION DATA:
- Duration: ${sessionData.duration}
- Messages exchanged: ${sessionData.messages}
- Topics: ${sessionData.topics.join(', ') || 'none'}
- Code files modified: ${sessionData.modifications.join(', ') || 'none'}
- Goals worked on: ${sessionData.goals.join(', ') || 'none'}
- Errors: ${sessionData.errors.length}
- Key decisions: ${sessionData.decisions.join('; ') || 'none'}

RECENT CONVERSATION:
${recentMessages || 'No conversation'}

Write TWO things:
1. SUMMARY: A 2-3 sentence summary of what happened this session (what you worked on, what was achieved, what was discussed).
2. UNFINISHED: One sentence about what was left incomplete or should be continued next time. Write "none" if everything was wrapped up.

Format:
SUMMARY: ...
UNFINISHED: ...`;

      const response = await this.model.chat(prompt, [], 'analysis');

      const summaryMatch = response.match(/SUMMARY:\s*(.+?)(?=UNFINISHED:|$)/is);
      const unfinishedMatch = response.match(/UNFINISHED:\s*(.+?)$/is);

      const summary = {
        date: new Date().toISOString(),
        duration: sessionData.duration,
        messageCount: sessionData.messages,
        summary: summaryMatch ? summaryMatch[1].trim() : response.slice(0, 300),
        unfinishedWork: unfinishedMatch ? unfinishedMatch[1].trim() : null,
        topics: sessionData.topics,
        filesModified: sessionData.modifications,
      };

      // Append to history
      this.sessionHistory.push(summary);
      if (this.sessionHistory.length > this.maxSessionHistory) {
        this.sessionHistory = this.sessionHistory.slice(-this.maxSessionHistory);
      }

      this._save();
      return summary;

    } catch (err) {
      // LLM unavailable — save raw session data instead
      const fallback = {
        date: new Date().toISOString(),
        duration: sessionData.duration,
        messageCount: sessionData.messages,
        summary: `Session with ${sessionData.messages} messages. Topics: ${sessionData.topics.join(', ') || 'none'}.`,
        unfinishedWork: null,
        topics: sessionData.topics,
        filesModified: sessionData.modifications,
      };
      this.sessionHistory.push(fallback);
      this._save();
      return fallback;
    }
  }

  /** Update user profile from observed patterns */
  updateUserProfile(updates) {
    if (updates.name) this.userProfile.name = updates.name;
    if (updates.language) this.userProfile.language = updates.language;
    // @ts-ignore — TS strict
    if (updates.interest && !this.userProfile.interests.includes(updates.interest)) {
      // @ts-ignore — TS strict
      this.userProfile.interests.push(updates.interest);
      if (this.userProfile.interests.length > 20) this.userProfile.interests.shift();
    }
    // @ts-ignore — TS strict
    if (updates.project && !this.userProfile.projects.includes(updates.project)) {
      // @ts-ignore — TS strict
      this.userProfile.projects.push(updates.project);
      if (this.userProfile.projects.length > 10) this.userProfile.projects.shift();
    }
    // @ts-ignore — TS strict
    if (updates.expertise && !this.userProfile.expertise.includes(updates.expertise)) {
      // @ts-ignore — TS strict
      this.userProfile.expertise.push(updates.expertise);
      if (this.userProfile.expertise.length > 15) this.userProfile.expertise.shift();
    }
    // @ts-ignore — TS strict
    this.userProfile.lastSeen = new Date().toISOString();
    this._debouncedSave();
  }

  getReport() {
    return {
      currentSession: {
        ...this.currentSession,
        duration: this._getSessionDuration(),
      },
      sessionHistory: this.sessionHistory.length,
      userProfile: { ...this.userProfile },
    };
  }

  // ════════════════════════════════════════════════════════
  // EVENT TRACKING
  // ════════════════════════════════════════════════════════

  _wireEvents() {
    this._unsubs.push(
      this.bus.on('user:message', (data) => {
        this.currentSession.messageCount++;
      }, { source: 'SessionPersistence', priority: -10 }),

      this.bus.on('intent:classified', (data) => {
        if (data?.type && data.type !== 'general' && data.type !== 'greeting') {
          // @ts-ignore — TS strict
          if (!this.currentSession.topicsDiscussed.includes(data.type)) {
            // @ts-ignore — TS strict
            this.currentSession.topicsDiscussed.push(data.type);
          }
        }
      }, { source: 'SessionPersistence', priority: -10 }),

      this.bus.on('chat:error', (data) => {
        this.currentSession.errorsEncountered.push(
          // @ts-ignore — TS strict
          (data?.message || 'unknown').slice(0, 100)
        );
      }, { source: 'SessionPersistence', priority: -10 }),

      this.bus.on('agent-loop:started', (data) => {
        if (data?.title) {
          // @ts-ignore — TS strict
          this.currentSession.goalsWorkedOn.push(data.title);
        }
      }, { source: 'SessionPersistence', priority: -10 }),

      // v4.12.5-fix: Was 'CODE_MODIFIED' — SelfModPipeline emits via EventStore.append(),
      // which fires 'store:CODE_MODIFIED'. Also handle bulk file list.
      this.bus.on('store:CODE_MODIFIED', (data) => {
        if (data?.file) {
          // @ts-ignore — TS strict
          this.currentSession.codeFilesModified.push(data.file);
        } else if (data?.files) {
          // @ts-ignore — TS strict
          this.currentSession.codeFilesModified.push(...data.files);
        }
      }, { source: 'SessionPersistence', priority: -10 }),

      // Learn user profile from conversation
      this.bus.on('memory:fact-stored', (data) => {
        if (data?.key === 'user.name' && data?.value) {
          this.updateUserProfile({ name: data.value });
        }
      }, { source: 'SessionPersistence', priority: -10 }),
    );
  }

  _getSessionDuration() {
    const started = new Date(this.currentSession.startedAt);
    const now = new Date();
    // @ts-ignore — TS strict
    const mins = Math.round((now - started) / 60000);
    return mins > 60 ? `${Math.round(mins / 60)}h ${mins % 60}m` : `${mins}m`;
  }

  // ════════════════════════════════════════════════════════
  // PERSISTENCE
  // ════════════════════════════════════════════════════════

  _save() {
    if (!this.storage) return;
    try {
      // v3.7.1: Non-blocking writes
      this.storage.writeJSONAsync('session-history.json', this.sessionHistory)
        .catch(err => _log.debug('[SESSION] History save error:', err.message));
      this.storage.writeJSONAsync('user-profile.json', this.userProfile)
        .catch(err => _log.debug('[SESSION] Profile save error:', err.message));
    } catch (err) { _log.debug('[SESSION] Save error:', err.message); }
  }

  _debouncedSave() {
    if (this._saveTimer) clearTimeout(this._saveTimer);
    this._saveTimer = setTimeout(() => this._save(), TIMEOUTS.PERSIST_DEBOUNCE);
  }

  /**
   * v3.8.0: Async boot-time data loading.
   * Called by Container.bootAll() after all services are resolved.
   * Replaces sync this._load() that was previously in the constructor.
   */
  async asyncLoad() {
    this._load();
  }


  _load() {
    if (!this.storage) return;
    try {
      const history = this.storage.readJSON('session-history.json', null);
      if (Array.isArray(history)) this.sessionHistory = history;

      const profile = this.storage.readJSON('user-profile.json', null);
      if (profile && typeof profile === 'object') {
        this.userProfile = { ...this.userProfile, ...profile };
      }
    } catch (err) { _log.debug('[SESSION] Load error:', err.message); }
  }

  // v5.9.9: Lifecycle compliance — unsubscribe listeners
  stop() {
    for (const unsub of this._unsubs) {
      try { if (typeof unsub === 'function') unsub(); } catch (_e) { /* ok */ }
    }
    this._unsubs.length = 0;
  }
}

module.exports = { SessionPersistence };
