// @ts-checked-v5.8
// ============================================================
// GENESIS — SessionPersistence.js (v3.5.0 — REVOLUTION)
//
// PROBLEM: Genesis loses almost everything between restarts.
// It knows the user's name (semantic memory) and has a journal,
// but it doesn't know:
// - What it was working on
// - What the user's project is about
// - What decisions were made
// - What it learned in the last session
//
// SOLUTION: At shutdown, Genesis creates a SESSION SUMMARY —
// a compressed narrative of what happened, generated by the LLM.
// At boot, this summary is loaded into the system prompt,
// giving Genesis immediate awareness of its recent history.
//
// Additionally, it maintains a USER PROFILE that accumulates
// across sessions: interests, preferences, project context,
// communication style, language.
//
// Architecture:
//   Shutdown → LLM summarizes session → saved to disk
//   Boot → summary loaded → injected into PromptBuilder
//   Continuous → user profile updated from conversation patterns
// ============================================================

const { NullBus } = require('../core/EventBus');
const { createLogger } = require('../core/Logger');
const { TIMEOUTS } = require('../core/Constants');
const _log = createLogger('SessionPersistence');

const { applySubscriptionHelper } = require('../core/subscription-helper');

class SessionPersistence {
  constructor({ bus, model, memory, storage, lang }) {
    this.bus = bus || NullBus;
    this.model = model;
    this.memory = memory;
    this.storage = storage || null;
    this.lang = lang || { t: k => k };

    // v7.1.4: Session ID for crash-safe checkpoint
    this._sessionId = `s-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;

    // ── Session State ────────────────────────────────────
    /** @type {{ startedAt: string, messageCount: number, topicsDiscussed: string[], errorsEncountered: string[], goalsWorkedOn: string[], keyDecisions: string[], codeFilesModified: string[] }} */
    this.currentSession = {
      startedAt: new Date().toISOString(),
      messageCount: 0,
      topicsDiscussed: [],
      errorsEncountered: [],
      goalsWorkedOn: [],
      keyDecisions: [],
      codeFilesModified: [],
    };

    // v7.1.4: Checkpoint interval (messages between saves)
    this._checkpointInterval = 10;

    // v7.1.5: EmotionalFrontier — late-bound (cross-layer bridge)
    this._emotionalFrontier = null;
    // v7.1.4: KnowledgeGraph — late-bound (frontier linking)
    this._knowledgeGraph = null;
    // v7.1.6: UnfinishedWorkFrontier — late-bound
    this._unfinishedWorkFrontier = null;
    // v7.1.6: GoalStack — late-bound (pending goals at session end)
    this._goalStack = null;

    // ── Persistent Across Sessions ───────────────────────
    this.sessionHistory = [];      // Last N session summaries
    this.maxSessionHistory = 10;
    /** @type {{ name: string|null, language: string|null, interests: string[], projects: string[], preferences: Record<string,*>, communicationStyle: string|null, expertise: string[], lastSeen: string|null }} */
    this.userProfile = {
      name: null,
      language: null,
      interests: [],
      projects: [],
      preferences: {},
      communicationStyle: null,
      expertise: [],
      lastSeen: null,
    };

    // v3.8.0: Moved to asyncLoad() — called by Container.bootAll()
    // this._load();
    /** @type {Array<Function>} */
    this._unsubs = [];
    this._wireEvents();
  }

  // ════════════════════════════════════════════════════════
  // PUBLIC API
  // ════════════════════════════════════════════════════════

  /**
   * Build a boot context for PromptBuilder.
   * Injected into the system prompt at startup so Genesis
   * immediately knows what happened in previous sessions.
   */
  buildBootContext() {
    const parts = [];

    // User profile
    if (this.userProfile.name) {
      parts.push(`USER: ${this.userProfile.name}`);
    }
    if (this.userProfile.language) {
      parts.push(`PREFERRED LANGUAGE: ${this.userProfile.language}`);
    }
    if (this.userProfile.projects.length > 0) {
      parts.push(`USER'S PROJECTS: ${this.userProfile.projects.slice(-3).join(', ')}`);
    }
    if (this.userProfile.expertise.length > 0) {
      parts.push(`USER EXPERTISE: ${this.userProfile.expertise.slice(-5).join(', ')}`);
    }

    // Last session summary
    if (this.sessionHistory.length > 0) {
      const last = this.sessionHistory[this.sessionHistory.length - 1];
      parts.push('');
      parts.push('LAST SESSION SUMMARY:');
      parts.push(last.summary || 'No summary available');
      if (last.unfinishedWork) {
        parts.push(`UNFINISHED WORK: ${last.unfinishedWork}`);
      }
    }

    // Session before last (for longer context)
    if (this.sessionHistory.length > 1) {
      const prev = this.sessionHistory[this.sessionHistory.length - 2];
      if (prev.summary) {
        parts.push('');
        parts.push(`EARLIER SESSION: ${prev.summary.slice(0, 200)}`);
      }
    }

    return parts.length > 0 ? parts.join('\n') : '';
  }

  /**
   * Generate session summary using the LLM.
   * Called during shutdown (before the model goes offline).
   */
  async generateSessionSummary(chatHistory = []) {
    if (this.currentSession.messageCount === 0 && chatHistory.length === 0) {
      return null;
    }

    // Build a compact session overview
    const sessionData = {
      duration: this._getSessionDuration(),
      messages: this.currentSession.messageCount,
      topics: this.currentSession.topicsDiscussed.slice(-10),
      errors: this.currentSession.errorsEncountered.slice(-5),
      goals: this.currentSession.goalsWorkedOn,
      modifications: this.currentSession.codeFilesModified,
      decisions: this.currentSession.keyDecisions.slice(-5),
    };

    // Get last few messages for context
    // v7.2.2: Guard against null content (tool calls, error responses).
    // Shutdown was crashing with "Cannot read properties of null (reading 'slice')".
    const recentMessages = chatHistory.slice(-10).map(m =>
      `${m.role}: ${(m.content || '').slice(0, 150)}`
    ).join('\n');

    try {
      const prompt = `You are Genesis. Your current session is ending. Create a brief summary for yourself to read when you restart.

SESSION DATA:
- Duration: ${sessionData.duration}
- Messages exchanged: ${sessionData.messages}
- Topics: ${sessionData.topics.join(', ') || 'none'}
- Code files modified: ${sessionData.modifications.join(', ') || 'none'}
- Goals worked on: ${sessionData.goals.join(', ') || 'none'}
- Errors: ${sessionData.errors.length}
- Key decisions: ${sessionData.decisions.join('; ') || 'none'}

RECENT CONVERSATION:
${recentMessages || 'No conversation'}

Write TWO things:
1. SUMMARY: A 2-3 sentence summary of what happened this session (what you worked on, what was achieved, what was discussed).
2. UNFINISHED: One sentence about what was left incomplete or should be continued next time. Write "none" if everything was wrapped up.

Format:
SUMMARY: ...
UNFINISHED: ...`;

      const response = await this.model.chat(prompt, [], 'analysis');

      const summaryMatch = response.match(/SUMMARY:\s*(.+?)(?=UNFINISHED:|$)/is);
      const unfinishedMatch = response.match(/UNFINISHED:\s*(.+?)$/is);

      const summary = {
        sessionId: this._sessionId,
        date: new Date().toISOString(),
        duration: sessionData.duration,
        messageCount: sessionData.messages,
        summary: summaryMatch ? summaryMatch[1].trim() : response.slice(0, 300),
        unfinishedWork: unfinishedMatch ? unfinishedMatch[1].trim() : null,
        topics: sessionData.topics,
        filesModified: sessionData.modifications,
        scores: this._computeScores(sessionData),
      };

      // Append to history
      this.sessionHistory.push(summary);
      if (this.sessionHistory.length > this.maxSessionHistory) {
        this.sessionHistory = this.sessionHistory.slice(-this.maxSessionHistory);
      }

      this._save();
      this._deleteCheckpoint(); // v7.1.4: clean up checkpoint after successful summary
      this._linkToFrontier(summary); // v7.1.4: connect summary to frontier
      return summary;

    } catch (err) {
      // LLM unavailable — save raw session data instead
      const fallback = {
        sessionId: this._sessionId,
        date: new Date().toISOString(),
        duration: sessionData.duration,
        messageCount: sessionData.messages,
        summary: `Session with ${sessionData.messages} messages. Topics: ${sessionData.topics.join(', ') || 'none'}.`,
        unfinishedWork: null,
        topics: sessionData.topics,
        filesModified: sessionData.modifications,
        scores: this._computeScores(sessionData),
      };
      this.sessionHistory.push(fallback);
      this._save();
      this._deleteCheckpoint(); // v7.1.4: clean up even on fallback
      this._linkToFrontier(fallback); // v7.1.4: connect fallback to frontier
      return fallback;
    }
  }

  /** Update user profile from observed patterns */
  updateUserProfile(updates) {
    if (updates.name) this.userProfile.name = updates.name;
    if (updates.language) this.userProfile.language = updates.language;
    if (updates.interest && !this.userProfile.interests.includes(updates.interest)) {
      this.userProfile.interests.push(updates.interest);
      if (this.userProfile.interests.length > 20) this.userProfile.interests.shift();
    }
    if (updates.project && !this.userProfile.projects.includes(updates.project)) {
      this.userProfile.projects.push(updates.project);
      if (this.userProfile.projects.length > 10) this.userProfile.projects.shift();
    }
    if (updates.expertise && !this.userProfile.expertise.includes(updates.expertise)) {
      this.userProfile.expertise.push(updates.expertise);
      if (this.userProfile.expertise.length > 15) this.userProfile.expertise.shift();
    }
    this.userProfile.lastSeen = new Date().toISOString();
    this._debouncedSave();
  }

  getReport() {
    return {
      currentSession: {
        ...this.currentSession,
        duration: this._getSessionDuration(),
      },
      sessionHistory: this.sessionHistory.length,
      userProfile: { ...this.userProfile },
    };
  }

  // ════════════════════════════════════════════════════════
  // EVENT TRACKING
  // ════════════════════════════════════════════════════════

  _wireEvents() {
    this._sub('user:message', (data) => {
      this.currentSession.messageCount++;
      // v7.1.4: Save checkpoint every N messages (crash-safe)
      if (this.currentSession.messageCount % this._checkpointInterval === 0) {
        this._saveCheckpoint();
      }
    }, { source: 'SessionPersistence', priority: -10 });

    this._sub('intent:classified', (data) => {
      if (data?.type && data.type !== 'general' && data.type !== 'greeting') {
        if (!this.currentSession.topicsDiscussed.includes(data.type)) {
          this.currentSession.topicsDiscussed.push(data.type);
        }
      }
    }, { source: 'SessionPersistence', priority: -10 });

    this._sub('chat:error', (data) => {
      this.currentSession.errorsEncountered.push(
        (data?.message || 'unknown').slice(0, 100)
      );
    }, { source: 'SessionPersistence', priority: -10 });

    this._sub('agent-loop:started', (data) => {
      if (data?.title) {
        this.currentSession.goalsWorkedOn.push(data.title);
      }
    }, { source: 'SessionPersistence', priority: -10 });

    // v4.12.5-fix: Was 'CODE_MODIFIED' — SelfModPipeline emits via EventStore.append(),
    // which fires 'store:CODE_MODIFIED'. Also handle bulk file list.
    // FIX v7.2.2: EventStore emits the full event object { id, type, payload, ... },
    // NOT just the payload. Previously read data.file (always undefined) — must
    // unwrap data.payload first. This caused codeFilesModified to be permanently empty.
    this._sub('store:CODE_MODIFIED', (data) => {
      const p = data?.payload || data; // unwrap EventStore envelope; fallback for direct emit
      if (p?.file) {
        this.currentSession.codeFilesModified.push(p.file);
      } else if (p?.files) {
        this.currentSession.codeFilesModified.push(...p.files);
      }
    }, { source: 'SessionPersistence', priority: -10 });

    // Learn user profile from conversation
    this._sub('memory:fact-stored', (data) => {
      if (data?.key === 'user.name' && data?.value) {
        this.updateUserProfile({ name: data.value });
      }
    }, { source: 'SessionPersistence', priority: -10 });
  }

  _getSessionDuration() {
    const started = new Date(this.currentSession.startedAt);
    const now = new Date();
    const mins = Math.round((now.getTime() - started.getTime()) / 60000);
    return mins > 60 ? `${Math.round(mins / 60)}h ${mins % 60}m` : `${mins}m`;
  }

  // ════════════════════════════════════════════════════════
  // v7.1.4 FEATURE 1: CRASH-SAFE CHECKPOINTS
  // ════════════════════════════════════════════════════════

  /** Save a lightweight checkpoint (no LLM). Called every _checkpointInterval messages. */
  _saveCheckpoint() {
    if (!this.storage) return;
    try {
      const checkpoint = {
        sessionId: this._sessionId,
        startTime: this.currentSession.startedAt,
        messageCount: this.currentSession.messageCount,
        topics: this.currentSession.topicsDiscussed.slice(-10),
        filesModified: [...new Set(this.currentSession.codeFilesModified)],
        decisions: this.currentSession.keyDecisions.slice(-5),
        errorCount: this.currentSession.errorsEncountered.length,
        goalsWorkedOn: this.currentSession.goalsWorkedOn.slice(-5),
        lastMessageTime: new Date().toISOString(),
        userName: this.userProfile.name,
      };
      this.storage.writeJSON('session-checkpoint.json', checkpoint);
      _log.debug(`[SESSION] Checkpoint saved (${checkpoint.messageCount} msgs, session ${this._sessionId})`);
    } catch (err) { _log.debug('[SESSION] Checkpoint save error:', err.message); }
  }

  /** Delete checkpoint after successful LLM summary. */
  _deleteCheckpoint() {
    if (!this.storage) return;
    try { this.storage.writeJSON('session-checkpoint.json', null); }
    catch (_e) { /* ok */ }
  }

  /** Recover from crash: if checkpoint exists but no matching summary, create fallback. */
  _recoverOrphanedCheckpoint() {
    if (!this.storage) return;
    try {
      const checkpoint = this.storage.readJSON('session-checkpoint.json', null);
      if (!checkpoint || !checkpoint.sessionId) return;

      // Check if this sessionId already has a summary
      const alreadySummarized = this.sessionHistory.some(s => s.sessionId === checkpoint.sessionId);
      if (alreadySummarized) {
        this._deleteCheckpoint();
        return;
      }

      // Orphaned checkpoint — crash occurred. Create fallback summary.
      _log.info(`[SESSION] Recovering orphaned checkpoint from crashed session ${checkpoint.sessionId}`);
      const fallback = {
        sessionId: checkpoint.sessionId,
        date: checkpoint.lastMessageTime || new Date().toISOString(),
        duration: 'unknown (crash)',
        messageCount: checkpoint.messageCount,
        summary: `Session crashed after ${checkpoint.messageCount} messages. Topics: ${(checkpoint.topics || []).join(', ') || 'none'}. Files: ${(checkpoint.filesModified || []).join(', ') || 'none'}.`,
        unfinishedWork: 'Session ended unexpectedly — review and continue.',
        topics: checkpoint.topics || [],
        filesModified: checkpoint.filesModified || [],
        scores: this._computeScores(checkpoint),
      };
      this.sessionHistory.push(fallback);
      if (this.sessionHistory.length > this.maxSessionHistory) {
        this.sessionHistory = this.sessionHistory.slice(-this.maxSessionHistory);
      }
      this._deleteCheckpoint();
      this._save();
    } catch (err) { _log.debug('[SESSION] Checkpoint recovery error:', err.message); }
  }

  // ════════════════════════════════════════════════════════
  // v7.1.4 FEATURE 3: SESSION SCORES (HEURISTIC)
  // ════════════════════════════════════════════════════════

  /** Compute deterministic session scores from metadata. No LLM needed. */
  _computeScores(data) {
    const messages = data.messageCount || data.messages || 0;
    const errors = data.errorCount ?? (data.errors ? data.errors.length : 0);
    const goals = data.goalsWorkedOn || data.goals || [];
    const goalsTotal = goals.length;
    const goalsCompleted = goalsTotal; // heuristic: if tracked, assumed completed
    const filesModified = data.filesModified || data.modifications || [];
    const decisions = data.decisions || [];

    return {
      productivity: goalsTotal > 0 ? Math.round(goalsCompleted / goalsTotal * 100) : (messages > 0 ? 50 : 0),
      complexity: Math.min(filesModified.length * 15 + decisions.length * 10, 100),
      quality: Math.max(0, Math.round(100 - (errors / Math.max(messages, 5)) * 200)),
      impact: filesModified.length > 0 ? Math.min(filesModified.length * 20, 100) : 10,
    };
  }

  /** Get rolling average of last N session scores for trend analysis. */
  getScoreTrends(window = 5) {
    const recent = this.sessionHistory.filter(s => s.scores).slice(-window);
    if (recent.length === 0) return null;
    const avg = { productivity: 0, complexity: 0, quality: 0, impact: 0 };
    for (const s of recent) {
      avg.productivity += s.scores.productivity;
      avg.complexity += s.scores.complexity;
      avg.quality += s.scores.quality;
      avg.impact += s.scores.impact;
    }
    const n = recent.length;
    return {
      productivity: Math.round(avg.productivity / n),
      complexity: Math.round(avg.complexity / n),
      quality: Math.round(avg.quality / n),
      impact: Math.round(avg.impact / n),
      sessions: n,
    };
  }

  // ════════════════════════════════════════════════════════
  // PERSISTENCE
  // ════════════════════════════════════════════════════════

  _save() {
    if (!this.storage) return;
    try {
      // v3.7.1: Non-blocking writes
      this.storage.writeJSONAsync('session-history.json', this.sessionHistory)
        .catch(err => _log.debug('[SESSION] History save error:', err.message));
      this.storage.writeJSONAsync('user-profile.json', this.userProfile)
        .catch(err => _log.debug('[SESSION] Profile save error:', err.message));
    } catch (err) { _log.debug('[SESSION] Save error:', err.message); }
  }

  _debouncedSave() {
    if (this._saveTimer) clearTimeout(this._saveTimer);
    this._saveTimer = setTimeout(() => this._save(), TIMEOUTS.PERSIST_DEBOUNCE);
  }

  /**
   * v3.8.0: Async boot-time data loading.
   * Called by Container.bootAll() after all services are resolved.
   * Replaces sync this._load() that was previously in the constructor.
   */
  async asyncLoad() {
    this._load();
    // v7.1.4: Recover from crash — check for orphaned checkpoint
    this._recoverOrphanedCheckpoint();
    // v7.1.4: Decay old frontier edges at boot (deterministic, no timer)
    if (this._knowledgeGraph) {
      this._knowledgeGraph.decayFrontierEdges(0.5);
    }
    // v7.1.5: Restore dampened emotional state from frontier imprints
    // Runs AFTER decay so imprint weights reflect their current relevance
    if (this._emotionalFrontier) {
      try {
        this._emotionalFrontier.restoreAtBoot();
      } catch (err) { _log.debug('[SESSION] Emotional restore error:', err.message); }
    }
  }

  /** v7.1.4: Link session summary to frontier node in KnowledgeGraph */
  _linkToFrontier(summary) {
    if (!this._knowledgeGraph) return;
    try {
      const label = `session-${this._sessionId}`;
      this._knowledgeGraph.connectToFrontier(
        'SESSION_COMPLETED', label, 1.0, 'session',
        { summary: (summary.summary || '').slice(0, 200), date: summary.date }
      );
      _log.debug(`[SESSION] Linked to frontier: ${label}`);
    } catch (err) { _log.debug('[SESSION] Frontier link error:', err.message); }

    // v7.1.5: Write emotional imprint alongside session link
    if (this._emotionalFrontier) {
      try {
        this._emotionalFrontier.writeImprint(this._sessionId, {
          topics: this.currentSession.topicsDiscussed,
          errors: this.currentSession.errorsEncountered,
        });
      } catch (err) { _log.debug('[SESSION] Emotional imprint error:', err.message); }
    }

    // v7.1.6: Write unfinished work to frontier
    if (this._unfinishedWorkFrontier) {
      try {
        this._unfinishedWorkFrontier.write(this._sessionId, {
          session: {
            messageCount: this.currentSession.messageCount,
            unfinishedWork: summary.unfinishedWork,
            codeFilesModified: this.currentSession.codeFilesModified,
            topicsDiscussed: this.currentSession.topicsDiscussed,
          },
          goalStack: this._goalStack,
        });
      } catch (err) { _log.debug('[SESSION] UnfinishedWork error:', err.message); }
    }
  }


  _load() {
    if (!this.storage) return;
    try {
      const history = this.storage.readJSON('session-history.json', null);
      if (Array.isArray(history)) this.sessionHistory = history;

      const profile = this.storage.readJSON('user-profile.json', null);
      if (profile && typeof profile === 'object') {
        this.userProfile = { ...this.userProfile, ...profile };
      }
    } catch (err) { _log.debug('[SESSION] Load error:', err.message); }
  }

  // v5.9.9: Lifecycle compliance — unsubscribe listeners
  stop() {
    this._unsubAll();
  }
}

applySubscriptionHelper(SessionPersistence);

module.exports = { SessionPersistence };
