// ============================================================
// GENESIS — Language.js
// Auto-detect user language, translate all user-facing text.
//
// Design decisions:
// - LLM prompts stay English (better performance on small models)
// - User-facing responses adapt to detected language
// - Detection from first user message, persisted in settings
// - Singleton pattern: require('./Language').lang
// ============================================================

const fs = require('fs');
const path = require('path');
const { safeJsonParse, atomicWriteFileSync } = require('./utils');
const { createLogger } = require('../core/Logger');
const _log = createLogger('Language');

class Language {
  constructor() {
    this.current = 'en'; // default
    this.confidence = 0;
    this.sampleCount = 0;
    this._settingsPath = null;
  }

  /** Point to settings dir for persistence */
  init(storageDir) {
    this._settingsPath = path.join(storageDir, 'language.json');
    try {
      if (fs.existsSync(this._settingsPath)) {
        const data = safeJsonParse(fs.readFileSync(this._settingsPath, 'utf-8'), {}, 'Language');
        if (data.lang && data.confidence > 0.3) {
          this.current = data.lang;
          this.confidence = data.confidence;
        }
      }
    } catch (err) { _log.debug('[LANG] Settings load failed:', err.message); }
  }

  /** Detect language from user text. Call on every user message. */
  detect(text) {
    if (!text || text.length < 3) return this.current;

    const scores = {};
    for (const [code, markers] of Object.entries(MARKERS)) {
      let score = 0;
      for (const { pattern, weight } of markers) {
        if (pattern.test(text)) score += weight;
      }
      if (score > 0) scores[code] = score;
    }

    const best = Object.entries(scores).sort((a, b) => b[1] - a[1])[0];

    if (best) {
      this.sampleCount++;
      // Exponential moving average for stability
      const alpha = Math.min(0.4, 1 / this.sampleCount);
      if (best[0] === this.current) {
        this.confidence = this.confidence * (1 - alpha) + 1.0 * alpha;
      } else if (best[1] > 3 || this.confidence < 0.4) {
        this.current = best[0];
        this.confidence = alpha;
      }
    }

    this._persist();
    return this.current;
  }

  /** Force a specific language */
  set(langCode) {
    if (STRINGS[langCode]) {
      this.current = langCode;
      this.confidence = 1.0;
      this._persist();
    }
  }

  /** Get current language code */
  get() { return this.current; }

  /** Translate a key. Falls back to English. Supports {{var}} interpolation. */
  t(key, vars = {}) {
    const dict = STRINGS[this.current] || STRINGS.en;
    let str = dict[key] || STRINGS.en[key] || key;
    for (const [k, v] of Object.entries(vars)) {
      str = str.replace(new RegExp(`{{${k}}}`, 'g'), String(v));
    }
    return str;
  }

  /** Get all strings for current language (for UI bulk transfer) */
  getUIStrings() {
    const en = STRINGS.en;
    const loc = STRINGS[this.current] || {};
    return { ...en, ...loc, _lang: this.current };
  }

  _persist() {
    if (!this._settingsPath) return;
    try {
      const dir = path.dirname(this._settingsPath);
      if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
      // FIX v5.1.0 (N-3): Atomic write for language settings.
      atomicWriteFileSync(this._settingsPath, JSON.stringify({
        lang: this.current, confidence: this.confidence,
      }), 'utf-8');
    } catch (err) { _log.debug('[LANG] Settings save failed:', err.message); }
  }
}

const MARKERS = {
  de: [
    { pattern: /\b(ich|mich|mir|mein|dein|sein|ihr|wir|uns|sie|ist|sind|hat|haben|kann|werden|nicht|auch|aber|oder|und|dass|wenn|weil|noch|schon|jetzt|hier|dort|diese|dieser|dieses)\b/i, weight: 2 },
    { pattern: /\b(bitte|danke|hallo|tschüss|moin|servus|guten|morgen|abend)\b/i, weight: 3 },
    { pattern: /[äöüßÄÖÜ]/, weight: 4 },
    { pattern: /\b(zeig|mach|gib|sag|hilf|finde|suche|erstell|reparier|verbess|analys)\w*/i, weight: 3 },
    { pattern: /\b(Datei|Fehler|Ergebnis|Einstellung|Verzeichnis|Ordner|Befehl)\b/i, weight: 3 },
  ],
  fr: [
    { pattern: /\b(je|tu|il|elle|nous|vous|ils|elles|est|sont|avoir|être|faire|aller|les|des|une|pas|que|qui|dans|pour|avec|sur|comme|mais|plus|très)\b/i, weight: 2 },
    { pattern: /\b(bonjour|merci|salut|bonsoir|oui|non|sil vous plaît|comment|pourquoi|quand|où)\b/i, weight: 3 },
    { pattern: /[àâæçéèêëîïôœùûüÿÀÂÆÇÉÈÊËÎÏÔŒÙÛÜŸ]/, weight: 4 },
  ],
  es: [
    { pattern: /\b(yo|tú|él|ella|nosotros|ustedes|ellos|es|son|tiene|hacer|estar|ser|ir|los|las|una|unos|que|por|para|como|pero|más|muy)\b/i, weight: 2 },
    { pattern: /\b(hola|gracias|buenas|buenos|sí|no|por favor|cómo|cuándo|dónde)\b/i, weight: 3 },
    { pattern: /[áéíóúñ¿¡ÁÉÍÓÚÑü]/i, weight: 4 },
  ],
  en: [
    { pattern: /\b(the|is|are|was|were|have|has|had|will|would|can|could|should|this|that|with|from|they|them|their|been|being|about|into|just|very|also|than)\b/i, weight: 1.5 },
    { pattern: /\b(please|thanks|hello|yes|no|why|how|what|when|where|which|would|could|should)\b/i, weight: 2 },
  ],
};

// ── Translation strings ─────────────────────────────────────

const STRINGS = {
  en: {
    // v7.9.3 Bug CC: previously-missing keys
    'health.active': 'Active',
    'health.inactive': 'Inactive',
    'health.idle': 'Idle',
    'health.status': 'Status',
    'health.thoughts': 'thoughts',
    'health.goals': 'goals',
    'health.active_goals': 'active goals',
    'ui.imported': 'Imported',
    'ui.self_modifying': 'Self-modifying...',
    'ui.thinking': 'Thinking...',
    'ui.warning': 'Warning',
    'ui.requires_restart': '(requires restart)',
    // UI
    'ui.booting': 'Booting...',
    'ui.ready': 'Ready',
    'ui.error': 'Error',
    'ui.starting': 'Starting...',
    'ui.placeholder': 'Message to Genesis...',
    'ui.editor': 'Editor',
    'ui.files': 'Files',
    'ui.status': 'Status',
    'ui.settings': 'Settings',
    'ui.undo': 'Undo',
    'ui.save': 'Save',
    'ui.run': 'Run in sandbox',
    'ui.project_structure': 'Project structure',
    'ui.no_file': 'No file open',
    'ui.no_model': 'No model',
    'ui.no_goals': 'No active goals',
    'ui.still_starting': 'Genesis is still starting...',
    'ui.saved': 'Saved: {{file}}',
    'ui.code_in_editor': 'Code in editor: {{file}}',
    'ui.model_switched': 'Model: {{model}}',
    'ui.switch_failed': 'Switch failed',
    'ui.settings_saved': 'Settings saved',
    'ui.settings_title': 'Settings',
    'ui.cancel': 'Cancel',
    'ui.daemon': 'Daemon',
    'ui.idle_mind': 'IdleMind',
    'ui.self_mod': 'Self-modification',
    'ui.active': 'Active',
    'ui.inactive': 'Off',
    'ui.allowed': 'Allowed',
    'ui.blocked': 'Blocked',
    // v7.4.7
    'ui.trust_level': 'Trust Level',
    'ui.trust_supervised': 'Supervised (always ask)',
    'ui.trust_assisted': 'Assisted (ask for risky)',
    'ui.trust_autonomous': 'Autonomous (ask only for critical)',
    'ui.trust_full': 'Full Autonomy (never ask)',
    'ui.auto_resume': 'Auto-Resume Open Goals',
    'ui.auto_resume_ask': 'Ask (Default)',
    'ui.auto_resume_always': 'Always resume',
    'ui.auto_resume_never': 'Never resume',
    'ui.mcp_serve': 'MCP Server (provide Genesis)',
    'ui.mcp_serve_off': 'Off',
    'ui.mcp_serve_on': 'On',
    'ui.mcp_port': 'MCP Server Port',
    'ui.approval_timeout': 'Approval Timeout in Seconds',
    'ui.takes_effect_after_restart': '(takes effect after restart)',
    // v7.4.7: Runtime toggle confirmation messages (chat:system-message)
    'ui.toggle.daemon_on':       'Daemon enabled.',
    'ui.toggle.daemon_off':      'Daemon disabled.',
    'ui.toggle.idlemind_on':     'IdleMind enabled.',
    'ui.toggle.idlemind_off':    'IdleMind disabled.',
    'ui.toggle.selfmod_on':      'Self-modification allowed.',
    'ui.toggle.selfmod_off':     'Self-modification blocked.',
    'ui.toggle.trust_level':     'Trust Level: {{level}}.',
    'ui.toggle.auto_resume':     'Auto-Resume Open Goals: {{mode}}.',
    'ui.toggle.mcp_started':     'MCP Server started on port {{port}}.',
    'ui.toggle.mcp_stopped':     'MCP Server stopped.',
    'ui.toggle.mcp_failed':      'MCP Server toggle failed: {{error}}',
    'ui.open_in_editor': 'Open in editor',
    'ui.file_opened': 'Opened: {{file}}',
    'ui.file_imported': 'Imported: {{file}}',
    'ui.drop_file': 'Drop file here',
    'ui.undo_success': 'Change reverted: {{detail}}',
    'ui.undo_failed': 'Undo failed: {{error}}',
    'ui.undo_nothing': 'Nothing to undo',
    'ui.goals': 'Goals',

    // Welcome
    'welcome.first': "I'm Genesis. I can understand my own source code, repair myself, develop new capabilities, and create improved clones.\n\nTell me your name and I'll remember you next time.",
    'welcome.returning': 'Hello {{name}}!',
    'welcome.returning_anon': "Hey! Good to have you back. What's on your mind?",
    'welcome.returning_familiar': "Hey! Good to see you again.",
    'welcome.working_on': 'What I\'m working on:',
    'welcome.thoughts': "I've had {{thoughts}} independent thoughts and know {{facts}} facts so far.",

    // Agent responses
    'agent.no_code_block': 'No code block found. Use ``` to wrap your code.',
    'agent.no_file': 'No file detected. Include a filename with extension.',
    'agent.file_not_found': 'File "{{file}}" not found.',
    'agent.cannot_execute': 'Cannot execute {{ext}}. Available runtimes: {{runtimes}}',
    'agent.shell_unavailable': 'ShellAgent not available.',
    'agent.no_command': 'No command detected. Write e.g. `$ git status` or "run npm test".',
    'agent.blocked_command': 'Blocked: {{reason}}',
    'agent.undo_only_one': 'Only one commit exists — cannot revert.',
    'agent.undo_conflict': 'Revert not possible — possible merge conflict. Manual fix: `git revert --abort` then `git reset --hard HEAD~1`.',
    'agent.undo_failed': 'Undo failed: {{error}}',
    'agent.undo_done': 'Reverted: `{{commit}}`',
    'agent.plan_failed': 'Could not create a plan.',
    'agent.plan_result': 'Result: {{ok}} succeeded, {{fail}} failed',
    'agent.no_output': '(no output)',
    'agent.error': 'Error',
    'agent.no_test_cmd': 'No test command detected for this project type.',
    'agent.no_install_cmd': 'No install command detected for this project type.',

    // Shell
    'shell.blocked_tier': 'Command blocked on tier "{{tier}}": {{cmd}}',
    'shell.permission_unknown': 'Unknown permission level: {{level}}',

    // Health
    'health.title': 'Genesis — System status',
    'health.kernel': 'Kernel',
    'health.intact': 'Intact',
    'health.problem': 'PROBLEM',
    'health.model': 'Model',
    'health.none': 'none',
    'health.modules': 'Modules',
    'health.skills': 'Skills',
    'health.tools': 'Tools',
    'health.memory': 'Memory',
    'health.facts': 'facts',
    'health.episodes': 'episodes',
    'health.daemon': 'Daemon',
    'health.cycles': 'cycles',
    'health.services': 'Services',
    'health.uptime': 'Uptime',
    'health.shell': 'Shell',
    'health.commands': 'commands',

    // Project scan
    'project.title': 'Project',
    'project.type': 'Type',
    'project.language': 'Language',
    'project.files': 'Files',
    'project.git': 'Git',
    'project.unknown': 'unknown',
    'project.no_git': 'no git',
    'project.commands': 'Available commands',
    'project.dependencies': 'Dependencies',
    'project.clean': 'clean',
    'project.changes': '{{n}} changes',

    // Tool descriptions
    'tool.file_info': 'File information',
    'tool.execute_file': 'Execute file',
    'tool.knowledge_search': 'Search knowledge graph',
    'tool.knowledge_connect': 'Connect concepts',
    'tool.event_query': 'Past events',
    'tool.web_fetch': 'Fetch a URL (documentation, API reference, npm packages)',
    'tool.npm_search': 'Search npm packages',
    'tool.web_ping': 'Check if a URL is reachable',
    'tool.shell_task': 'Plan and execute a complex system task in multiple steps (with safety tiers, git snapshots, and recipe learning)',

    // MCP (Model Context Protocol)
    'mcp.connecting': 'Connecting to MCP server {{name}}...',
    'mcp.connected': 'MCP server {{name}} connected ({{tools}} tools)',
    'mcp.disconnected': 'MCP server {{name}} disconnected',
    'mcp.error': 'MCP error ({{name}}): {{error}}',
    'mcp.no_servers': 'No MCP servers configured',
    'mcp.server_added': 'MCP server **{{name}}** added ({{url}})',
    'mcp.server_removed': 'MCP server **{{name}}** removed',
    'mcp.tools_discovered': '{{count}} tools discovered from {{name}}',
    'mcp.tool_call_failed': 'MCP tool call failed: {{error}}',
    'mcp.status_title': 'MCP Status',
    'mcp.servers': 'Servers',
    'mcp.total_tools': 'Total tools',

    // Inspect / Self-report
    'inspect.title': 'Genesis — Self-report',
    'inspect.identity': 'Identity',
    'inspect.modules': 'Modules',
    'inspect.files': 'files',
    'inspect.kernel': 'Kernel',
    'inspect.kernel_intact': 'Intact',
    'inspect.kernel_compromised': 'COMPROMISED',
    'inspect.capabilities': 'Capabilities',
    'inspect.skills': 'Skills',
    'inspect.none': 'none',
    'inspect.tools': 'Tools',
    'inspect.tools_registered': 'registered',
    'inspect.model': 'Model',
    'inspect.modules_header': 'Modules',
    'inspect.protected': 'protected',

    // Chat status
    'chat.error': 'Error: {{message}}',
    'chat.tools_executing': 'Executing tools...',
    'chat.no_revertable_commit': 'No revertable commit available',

    // Shell
    'shell.plan_error': 'Planning error: {{message}}',
    'shell.step_skipped': 'Previous step failed',

    // Goals
    'goal.no_code': 'No code generated',
    'goal.file_requested': 'File creation requested: {{detail}}',
    'goals.unavailable': 'GoalStack not available.',
    'goals.created': 'New goal created: **{{description}}**',
    'goals.steps': 'Steps',
    'goals.empty': 'No goals set yet. Say e.g. "/goal add Improve error handling"',
    'goals.title': 'Goals',
    'goals.next_step': 'Next step',
    // v7.5.0 — slash-discipline + negotiation
    'goals.add_empty': 'Empty goal description. Try: /goal add <description>',
    'goals.add_failed': 'Could not create goal.',
    'goals.cancel_needs_number': 'Which goal? Try: /goal cancel <n>  (use /goal list for numbers)',
    'goals.cancel_one_done': '**Goal cancelled:** {{description}}',
    'goals.cancel_one_not_found': '**Goal #{{idx}} not found.** {{count}} active goals.',
    'goals.cancel_all_confirm': 'Confirm: cancel all {{count}} active goals? Send `/goal clear` again within 30 seconds to confirm.',
    'goals.cancel_all_done': '**{{count}} goal(s) cancelled.**',
    'goals.none_active': '**No active goals.**',
    'goals.unknown_subcommand': 'Unknown subcommand: `{{sub}}`. Try `/goal list`, `/goal add <text>`, `/goal cancel <n>`, `/goal clear`.',
    'goals.help': '**Goal commands:**\n- `/goal list` — show goals\n- `/goal add <text>` — add a goal\n- `/goal cancel <n>` — cancel goal #n\n- `/goal clear` — cancel all (asks confirmation)\n- `/goal confirm <id>` — confirm pending proposal\n- `/goal revise <id>: <text>` — revise pending\n- `/goal dismiss <id>` — drop pending',
    'goals.proposed': 'Goal proposed: **"{{description}}"**. Genesis is reviewing it before it becomes active.\n\nUse `/goal confirm {{pendingId}}` to accept, `/goal revise {{pendingId}}: <new text>` to refine, or `/goal dismiss {{pendingId}}` to drop.',
    'goals.confirmed': 'Goal confirmed and added: **{{description}}**',
    'goals.revised': 'Proposal revised: **"{{description}}"** (`{{pendingId}}`). Genesis will review again.',
    'goals.dismissed': 'Proposal dismissed: {{description}}',
    'goals.pending_id_missing': 'Pending ID missing. Use `/goal list` to see pending IDs.',
    'goals.pending_not_found': 'Pending proposal `{{pendingId}}` not found (may have expired after 1h).',
    'goals.pending_title': 'Pending (awaiting confirmation)',
    'goals.confirm_failed': 'Could not confirm: {{error}}',
    'goals.revise_format': 'Format: `/goal revise <id>: <new description>`',
    'goals.negotiation_unavailable': 'Goal negotiation is not available in this build.',

    // Peers
    'peer.none_found': 'No peers found.',
    'peer.none_hint': 'No peers. Say "peer scan" to discover.',
    'peer.found': 'found',

    // Daemon
    'daemon.stopped': 'Daemon stopped.',
    'daemon.started': 'Daemon started.',

    // Journal & Plans
    'journal.empty': 'No thoughts in the journal yet.',
    'journal.last': 'last {{n}}',
    'plans.empty': 'No improvement plans yet. I think about them when idle.',
    'plans.title': 'Improvement plans',

    // Settings
    'settings.unavailable': 'Settings not available.',
    'settings.api_key_saved': 'Anthropic API key saved ({{key}}...). Restart to activate.',
    'settings.not_configured': 'not configured',
    'settings.preferred_model': 'Preferred model',
    'settings.every_n_min': 'every {{n}} min',
    'settings.idle_after_min': 'idle after {{n}} min',
    'settings.api_key_hint': 'Say e.g. "Anthropic API-Key: sk-ant-..." to set a key.',

    // Web
    'web.unavailable': 'Web access not available.',
    'web.npm_failed': 'npm search failed: {{error}}',
    'web.npm_no_results': 'No packages found for: {{query}}',
    'web.fetch_failed': 'Could not fetch {{url}}: {{error}}',
    'web.reachable': '**{{url}}** is reachable (status {{status}})',
    'web.unreachable': '**{{url}}** is not reachable: {{error}}',
    'web.hint': 'Provide a URL, or say e.g. "npm search express" or "check if nodejs.org is reachable".',

    // MCP extended
    'mcp.unavailable': 'MCP not available.',
    'mcp.server_not_found': 'Server "{{name}}" not found.',
    'mcp.server_started': 'Genesis MCP server started on **port {{port}}**.\nOther agents: `http://127.0.0.1:{{port}}`',
    'mcp.server_start_failed': 'MCP server start failed: {{error}}',
    'mcp.no_tools_found': 'No MCP tools found for "{{query}}".',
    'mcp.connect_hint': 'Say e.g.: `mcp connect github https://mcp.github.com/sse`',

    // Self-modification
    'selfmod.applied': 'Modification applied.',
    'selfmod.files': 'Files',
    'selfmod.all_intact': 'All systems intact.',
    'selfmod.tests_failed': 'Tests failed:',
    'selfmod.astdiff_applied': 'Precise modification (ASTDiff) applied:',
    'selfmod.warnings': 'Warnings',
    'selfmod.repair': 'Repair',
    'selfmod.greeting': "Hey! What can I do for you?",

    // v7.5.7-fix Phase 3 Etappe 2/3: settings UI labels and options
    'ui.on': 'On',
    'ui.off': 'Off',
    'ui.on_default': 'On (Default)',
    'ui.off_default': 'Off (Default)',
    'ui.allowed_default': 'Allowed (Default)',
    'ui.add': 'Add',
    'ui.remove': 'Remove',
    'ui.reset_to_default': 'Reset to default',
    'ui.panel_widths': 'Panel widths',
    'ui.reset_panel_widths': 'Reset panel widths to default',
    'settings.section.layout': 'Layout',
    'settings.layout.panels.hint': 'Sets file-tree, goals and editor panels back to their default widths. The chat panel always fills the remaining space.',

    // Section headers
    'settings.section.cost_guard': 'Cost protection (Cost-Guard)',
    'settings.section.eventstore_rotation': 'EventStore rotation',
    'settings.section.worker_spawner': 'Worker & Spawner',
    'settings.section.memory_extra': 'Additional memory',
    'settings.section.daemon_behavior': 'Daemon behaviour',
    'settings.section.idle_mind': 'IdleMind',
    'settings.section.security': 'Security',
    'settings.section.health_server': 'Health server',
    'settings.section.ui_display': 'UI display',
    'settings.section.mcp_external': 'External MCP servers (connect)',

    // Field labels
    'settings.cost_guard.enabled': 'Cost-Guard active',
    'settings.cost_guard.session_limit': 'Session limit (tokens)',
    'settings.cost_guard.daily_limit': 'Daily limit (tokens)',
    'settings.cost_guard.warn_threshold': 'Warning at (%)',
    'settings.eventstore.size': 'Maximum file size (MB)',
    'settings.eventstore.rotations': 'Number of rotations',
    'settings.spawner.timeout': 'SelfSpawner timeout (seconds)',
    'settings.spawner.memory': 'SelfSpawner memory limit (MB)',
    'settings.workerpool.max': 'Worker pool threads',
    'settings.episodic.max': 'EpisodicMemory maximum',
    'settings.idlemind.journal_size': 'IdleMind journal — max size (MB)',
    'settings.idlemind.journal_rotations': 'IdleMind journal — rotations',
    'settings.idlemind.max_goals': 'Maximum active goals',
    'settings.daemon.auto_repair': 'Auto-repair',
    'settings.daemon.auto_optimize': 'Auto-optimize',
    'settings.security.allow_peers': 'Allow peer network',
    'settings.security.allow_file_exec': 'Allow file execution',
    'settings.agency.commit_on_shutdown': 'Git snapshot on shutdown',
    'settings.health.http_enabled': 'HTTP health server',
    'settings.health.http_port': 'HTTP health port',
    'settings.ui.editor_font': 'Editor font size (px)',
    'settings.ui.chat_font': 'Chat font size (px)',
    'settings.openai.models': 'OpenAI model names (comma-separated)',
    'settings.mcp.list': 'MCP server list',
    'settings.mcp.empty': 'No MCP servers configured.',
    'settings.mcp.placeholder_name': 'Name (e.g. github-mcp)',
    'settings.mcp.placeholder_url': 'URL (https://… or stdio://…)',
    'settings.validation.out_of_range': 'Value out of valid range. Save blocked.',
    'settings.validation.toast': 'Some values are out of valid range. Please correct them.',

    // v7.5.7-fix Phase 3 Etappe 5 — full i18n coverage
    'settings.tab.models': 'Models',
    'settings.tab.behavior': 'Behaviour',
    'settings.tab.limits': 'Limits',
    'settings.tab.mcp': 'MCP',
    'settings.tab.advanced': 'Advanced',
    'settings.tab.json': 'JSON Editor',
    'settings.loading': 'Loading...',
    'settings.auto_detect': 'Auto-detect',
    'settings.model_roles': 'Model Roles',
    'settings.roles_hint': 'Only takes effect when auto-routing is active (see Behaviour tab).',
    'settings.fallback_chain': 'Fallback Chain',
    'settings.fallback_help': 'Models tried in order if primary fails',
    'settings.fallback_click_to_add': 'Click',
    'settings.fallback_to_add': 'to add',
    'settings.fallback_available': 'Available Models',
    'settings.fallback_your_chain': 'Your Chain',
    'settings.fallback_empty': 'No fallback models — Genesis will fail if primary breaks.',
    'settings.anthropic_key': 'Anthropic API Key',
    'settings.openai_url': 'OpenAI-compatible API URL',
    'settings.openai_key': 'OpenAI API Key',
    'settings.openai.models_hint': 'Models used as OpenAI backend. Empty = auto-detect (if supported). Comma-separated.',
    'settings.opt.active': 'Active',
    'settings.opt.off': 'Off',
    'settings.opt.allowed': 'Allowed',
    'settings.opt.blocked_local': 'Blocked',
    'settings.opt.on': 'On',
    'settings.opt.on_default': 'On (Default)',
    'settings.opt.off_default': 'Off (Default)',
    'settings.opt.allowed_default': 'Allowed (Default)',
    'settings.autoroute.off': 'Off — always use Preferred Model',
    'settings.autoroute.on': 'On — auto-pick model per task',
    'settings.autoroute.hint': 'When on: Genesis picks a different model per task type from your list. May keep multiple models in RAM at once.',
    'settings.negotiate.off': 'Off — Goal active immediately',
    'settings.negotiate.on': 'On — clarify first, then activate',
    'settings.negotiate.label': 'Goal negotiation before adding',
    'settings.cogstrict.off': 'Off — AgentLoop runs even without all cognitive services',
    'settings.cogstrict.on': 'On — AgentLoop requires verifier/formalPlanner/worldState',
    'settings.cogstrict.label': 'Cognitive Strict Mode',
    'settings.section.koennen': 'Können-Konzept (Skill Crystallization)',
    'settings.koennen.enabled.label': 'Können pipeline',
    'settings.koennen.enabled.on': 'On (Default) — affect-encoding + crystallization active',
    'settings.koennen.enabled.off': 'Off — no skill extraction from trajectories',
    'settings.koennen.enabled.hint': 'Master toggle for the whole Können concept. When off: KoennenCandidateLog and SkillCrystallizer don\'t run.',
    'settings.koennen.cryst.enabled.label': 'Skill crystallization (Phase 2)',
    'settings.koennen.cryst.enabled.on': 'On (Default) — DreamCycle Phase 3c extracts skills',
    'settings.koennen.cryst.enabled.off': 'Off — trajectories are logged, but nothing crystallized',
    'settings.koennen.cryst.enabled.hint': 'Only effective when the master toggle above is on. Uses LLM calls — turn off if token budget is tight.',
    'settings.koennen.cryst.minCandidates.label': 'Min. candidates per pattern',
    'settings.koennen.cryst.minCandidates.hint': 'How many similar gate-passed trajectories are needed before a skill is extracted. Default: 3. Higher = more conservative.',
    'settings.koennen.cryst.cooldown.label': 'Pattern cooldown (ms)',
    'settings.koennen.cryst.cooldown.hint': 'How long a failed pattern is blocked before being retried. Default: 21600000 ms (= 6 h).',
    'settings.autoroute.label': 'Auto-routing for background tasks',
    'settings.daemon_repair.off': 'Off — detect only, don\'t repair',
    'settings.daemon_repair.on': 'On (Default) — auto-repairs detected bugs',
    'settings.daemon_repair.hint': 'Default: on. ImmuneSystem detects problems; with Auto-Repair active, they get repaired too. Off: detection only, no action.',
    'settings.daemon_optimize.off': 'Off (Default) — suggestions only, no optimizations',
    'settings.daemon_optimize.on': 'On — applies suggested optimizations autonomously',
    'settings.daemon_optimize.hint': 'Default: off. Daemon proposes optimizations; on applies them without confirmation. Caution — may change behaviour.',
    'settings.idlemind.max_goals.hint': 'How many goals IdleMind may pursue in parallel. Default: 3.',
    'settings.security.peers.hint': 'Default: on. When off: Genesis accepts no peer connections for skill/memory exchange.',
    'settings.security.fileexec.hint': 'Default: on. When off: Genesis can\'t execute external files (Python/Shell).',
    'settings.commit_shutdown.off': 'Off (Default) — no auto-commit',
    'settings.commit_shutdown.on': 'On — commits .genesis/ on every shutdown',
    'settings.commit_shutdown.hint': 'Default: off (v7.5.7-fix Phase 3). On a shared repo: leave off, otherwise Genesis files end up in your git history.',
    'settings.agency.git_auto_init': 'Git auto-initialize repository',
    'settings.git_auto_init.off': 'Off (Default) — never run "git init"',
    'settings.git_auto_init.on': 'On — run "git init" if no repo exists',
    'settings.git_auto_init.hint': 'Default: off (v7.7.1-hotfix). Genesis will not create a .git directory without your consent. Your existing repo is never touched.',
    'settings.agency.git_auto_commit': 'Git auto-commit on self-modification',
    'settings.git_auto_commit.off': 'Off (Default) — no automatic commits',
    'settings.git_auto_commit.on': 'On — Genesis commits before/after self-modifications',
    'settings.git_auto_commit.hint': 'Default: off (v7.7.1-hotfix). SnapshotManager and GenesisBackup are the active fallback layers covering the same use case via file-copy without touching git.',
    // v7.5.9 ZIP6 — Software-installation settings.
    'settings.section.install': 'Software Installation (v7.5.9 ZIP 5)',
    'settings.install.allow_auto.label': 'Auto-Install via Package Manager (Tier 1+2)',
    'settings.install.allow_auto.off': 'Off (Default) — preview-only',
    'settings.install.allow_auto.on': 'On — execute winget/choco/brew/apt automatically, plus PM bootstrap if missing',
    'settings.install.allow_auto.hint': 'When on + Trust ≥ AUTONOMOUS: Genesis installs via Package Manager without confirmation. If the PM is missing, Genesis tries to bootstrap one. Default: off.',
    'settings.install.full_autonomy.label': 'Full Install Autonomy (Tier 3 — Direct Download)',
    'settings.install.full_autonomy.off': 'Off (Default) — no automatic download',
    'settings.install.full_autonomy.on': 'On — Genesis downloads installers from official vendor URLs and launches them',
    'settings.install.full_autonomy.hint': 'Only effective when Auto-Install is also on. If on: "install X" makes Genesis download files (winrar, vscode, firefox, chrome, git, python, nodejs, vlc, 7zip, notepad++) to Downloads and launch the installer. You only need to click the Windows UAC dialog — that one cannot be automated. Default: off.',
    'settings.install.scope.label': 'Install target (winget --scope)',
    'settings.install.scope.machine': 'Machine — system-wide in C:\\Program Files\\ (Default, requires admin prompt)',
    'settings.install.scope.user': 'User — per-user in AppData\\ (no admin needed)',
    'settings.install.scope.auto': 'Auto — let winget decide (some packages ignore --scope)',
    'settings.install.scope.hint': 'Determines where winget places software. "Machine" raises an admin prompt but lands in Program Files. "User" is admin-free but lands in AppData (sometimes only as a .lnk). Some packages (like WinRAR) ignore --scope and always install in the same area. Per-call overrideable with /install <name> <path> (e.g., /install winrar D:\\Programme\\WinRAR).',
    'settings.section.memory_caps': 'Memory Caps',
    'settings.section.timeouts': 'Timeouts',
    'settings.maxconcurrent.label': 'Maximum concurrent LLM requests',
    'settings.maxconcurrent.hint': 'How many LLM requests may run in parallel. High = more parallelism, can cause CPU thrashing. Default: 3.',
    'settings.maxworkers.label': 'Maximum parallel worker processes',
    'settings.maxworkers.hint': 'How many worker subprocesses SelfSpawner may fork in parallel. Default: 3.',
    'settings.keepalive.label': 'Ollama Keep-Alive',
    'settings.kg.label': 'KnowledgeGraph maximum (nodes)',
    'settings.kg.hint': 'Max number of nodes in the knowledge graph. On overflow the oldest/rarest is removed. 0 = unlimited.',
    'settings.sslog.label': 'SelfStatementLog maximum',
    'settings.sslog.hint': 'Max number of self-statements total. On overflow the oldest are pruned. 0 = unlimited.',
    'settings.approval_timeout.label': 'Approval Timeout (seconds)',
    'settings.approval_timeout.hint': 'How long Genesis waits for an approval reply before aborting.',
    'settings.cost_guard.enabled.hint': 'Protects against unbounded LLM costs from IdleMind/DreamCycle/Daemon. User chat is never blocked, only autonomous calls. Default: on.',
    'settings.cost_guard.session.hint': 'Token budget per session. Default: 500,000.',
    'settings.cost_guard.daily.hint': 'Token budget per day (resets at midnight). Default: 2,000,000.',
    'settings.cost_guard.warn.hint': 'Percentage of the limit at which to warn. Default: 80.',
    'settings.eventstore.size.hint': 'On overflow events.jsonl is rotated (.1, .2, ...). 0 = no rotation. Default: 50.',
    'settings.eventstore.rot.hint': 'How many rotated files to keep. 0 = none. Default: 3.',
    'settings.spawner.timeout.hint': 'Maximum runtime of a worker process before it is killed. Default: 300s (5 min).',
    'settings.spawner.memory.hint': 'Maximum RAM per worker process. Default: 256 MB.',
    'settings.workerpool.hint': 'Number of worker threads for GenericWorker (code analysis etc.). 0 = automatic (CPU cores − 1). Default: 0.',
    'settings.episodic.hint': 'Max number of stored episodes. 0 = unlimited. Default: 500.',
    'settings.idlemind.journal_size.hint': 'On overflow IdleMind journal is rotated. Default: 10.',
    'settings.idlemind.journal_rot.hint': 'How many rotated journal files to keep. Default: 3.',
    'settings.mcp.serve.label': 'MCP Server (provide Genesis)',
    'settings.mcp.port.label': 'MCP Server Port',
    'settings.mcp.list_hint': 'External MCP servers to connect to. Genesis calls their tools via mcp-call. Changes take effect on save.',
    'settings.cogsim.branches': 'Cognitive Simulation — Max Branches',
    'settings.cogsim.depth': 'Cognitive Simulation — Max Depth',
    'settings.emotion.decay.label': 'Emotion decay interval (seconds)',
    'settings.emotion.decay.hint': 'How often emotions drift toward baseline. Default 60s. Lower = faster calming, higher = more stable moods.',
    'settings.loneliness.label': 'Loneliness growth interval (seconds)',
    'settings.loneliness.hint': 'How often loneliness grows passively when no interaction. Default 300s (5min).',
    'settings.idlemind.idle': 'IdleMind — Idle threshold (minutes)',
    'settings.idlemind.think': 'IdleMind — Think interval (minutes)',
    'settings.daemon.cycle': 'Daemon — Cycle (minutes)',
    'settings.health.http.hint': 'Default: off. When on: Genesis exposes /health, /metrics, /events HTTP endpoints for external monitoring.',
    'settings.health.port.hint': 'Port for the health server. Default: 9090.',
    'settings.ui.editor_font.hint': 'Font size in the code editor. Default: 13.',
    'settings.ui.chat_font.hint': 'Font size in the chat area. Default: 13.',
    // v7.5.7-fix Phase 3 Etappe 6 — final i18n coverage
    'default_hint.label': 'Default',
    'default_hint.min': 'Min',
    'default_hint.max': 'Max',
    'default_hint.on': 'on',
    'default_hint.off': 'off',
    'default_hint.empty': 'empty',
    'default_hint.not_a_number': 'not a number',
    'settings.validation.out_of_range_with_reason': 'Value out of valid range ({{reason}}). Save blocked.',
    'settings.active_model': 'Active Model',
    'settings.role.chat': 'Chat',
    'settings.role.code': 'Code',
    'settings.role.analysis': 'Analysis',
    'settings.role.creative': 'Creative',
    'settings.api_keys': 'API Keys',
    'settings.keepalive.placeholder': '(Ollama default: 5m)',
    'settings.keepalive.hint': 'How long Ollama keeps a model in RAM after the last call. Examples: <code>30s</code>, <code>5m</code>, <code>1h</code>, <code>0</code> (unload immediately), <code>-1</code> (forever). Empty = Ollama default (5min).',
    'settings.fallback_instructions': 'Click <strong>Add</strong> to put a model in the chain. Use <strong>↑ ↓</strong> to reorder, <strong>×</strong> to remove. <span class="cloud-hint">☁ = cloud (may need subscription)</span>',
    // v7.5.7-fix Phase 3 Etappe 7 — JS-generated text i18n
    'settings.mcp.error_name_missing': 'MCP server: name missing',
    'settings.mcp.error_url_missing': 'MCP server: URL missing',
    'settings.mcp.error_exists': 'MCP server "{name}" already exists',
    'settings.json.status_loaded': 'loaded',
    'settings.json.status_load_error': 'Load failed',
    'settings.json.status_valid': 'JSON valid',
    'settings.json.status_invalid': 'Invalid',
    // JSON-Editor (Etappe 4)
    'settings.json.title': 'JSON Editor (power mode)',
    'settings.json.help': 'Direct access to all settings — including the ~50 not visible in the UI (cognitive sub-flags, organism tuning, peer.discoveryToken, etc.). API keys are masked here; set them via the Models tab. Invalid JSON will not be saved.',
    'settings.json.validate': 'Validate',
    'settings.json.reload': 'Reload',
    // v7.9.4: Können Phase 3 — promotion, rehearsal, acquisitionContext
    'settings.koennen_acquisition_context_enabled': 'Generate biography for new skills',
    'settings.koennen_acquisition_context_help': 'When a skill is crystallized, Genesis writes one sentence on what would have been the gap without it. One small LLM call per crystallization.',
    'settings.koennen_rehearsal_enabled': 'Rehearse pending skills during idle',
    'settings.koennen_rehearsal_help': 'When idle, Genesis picks a pending skill and runs it with a generated input to gather effectiveness data.',
    'settings.koennen_promotion_enabled': 'Allow Genesis to promote his own skills',
    'settings.koennen_promotion_help': 'When a skill meets all four maturity criteria, Genesis promotes it from pending to productive use.',
    'settings.koennen_promotion_min_invocations': 'Minimum rehearsals before promotion',
    'settings.koennen_promotion_min_wilson_lb': 'Minimum Wilson lower bound',
    'settings.koennen_promotion_min_distinct_inputs': 'Minimum distinct rehearsal inputs',
    'settings.koennen_promotion_min_age_hours': 'Minimum skill age in hours',
    'koennen.toast_promoted': 'Acquired skill: {{name}}',
    'koennen.toast_discarded': 'Released skill: {{name}}',
    'koennen.toast_quarantined': 'Quarantined skill: {{name}}',
    'koennen.toast_discard_suggested': 'Considering letting go: {{name}}',
    'koennen.no_biography': 'No biography (crystallized before v7.9.4)',
    'koennen.status_promoted': 'Promoted',
    'koennen.status_rehearsing': 'Rehearsing',
    'koennen.status_pending': 'Pending',
    'koennen.status_quarantined': 'Quarantined',
    'koennen.status_discarded': 'Discarded',
  },

  de: {
    // v7.9.3 Bug CC: previously-missing keys
    'health.active': 'Aktiv',
    'health.inactive': 'Inaktiv',
    'health.idle': 'Untätig',
    'health.status': 'Status',
    'health.thoughts': 'Gedanken',
    'health.goals': 'Ziele',
    'health.active_goals': 'aktive Ziele',
    'ui.imported': 'Importiert',
    'ui.self_modifying': 'Selbstmodifikation...',
    'ui.thinking': 'Denke nach...',
    'ui.warning': 'Warnung',
    'ui.requires_restart': '(Neustart erforderlich)',
    'ui.booting': 'Startet...',
    'ui.ready': 'Bereit',
    'ui.error': 'Fehler',
    'ui.starting': 'Startet...',
    'ui.placeholder': 'Nachricht an Genesis...',
    'ui.editor': 'Editor',
    'ui.files': 'Dateien',
    'ui.status': 'Status',
    'ui.settings': 'Einstellungen',
    'ui.undo': 'Rückgängig',
    'ui.save': 'Speichern',
    'ui.run': 'In Sandbox ausführen',
    'ui.project_structure': 'Projektstruktur',
    'ui.no_file': 'Keine Datei geöffnet',
    'ui.no_model': 'Kein Modell',
    'ui.no_goals': 'Keine aktiven Ziele',
    'ui.still_starting': 'Genesis startet noch...',
    'ui.saved': 'Gespeichert: {{file}}',
    'ui.code_in_editor': 'Code im Editor: {{file}}',
    'ui.model_switched': 'Modell: {{model}}',
    'ui.switch_failed': 'Wechsel fehlgeschlagen',
    'ui.settings_saved': 'Einstellungen gespeichert',
    'ui.settings_title': 'Einstellungen',
    'ui.cancel': 'Abbrechen',
    'ui.daemon': 'Daemon',
    'ui.idle_mind': 'IdleMind',
    'ui.self_mod': 'Selbst-Modifikation',
    'ui.active': 'Aktiv',
    'ui.inactive': 'Aus',
    'ui.allowed': 'Erlaubt',
    'ui.blocked': 'Gesperrt',
    // v7.4.7
    'ui.trust_level': 'Vertrauensstufe',
    'ui.trust_supervised': 'Überwacht (immer fragen)',
    'ui.trust_assisted': 'Assistiert (bei Risiko fragen)',
    'ui.trust_autonomous': 'Autonom (nur bei Kritischem fragen)',
    'ui.trust_full': 'Volle Autonomie (nie fragen)',
    'ui.auto_resume': 'Auto-Resume offener Ziele',
    'ui.auto_resume_ask': 'Fragen (Standard)',
    'ui.auto_resume_always': 'Immer fortsetzen',
    'ui.auto_resume_never': 'Nie fortsetzen',
    'ui.mcp_serve': 'MCP-Server (Genesis bereitstellen)',
    'ui.mcp_serve_off': 'Aus',
    'ui.mcp_serve_on': 'An',
    'ui.mcp_port': 'MCP-Server Port',
    'ui.approval_timeout': 'Approval-Timeout in Sekunden',
    'ui.takes_effect_after_restart': '(wirkt nach Neustart)',
    // v7.4.7
    'ui.toggle.daemon_on':       'Daemon aktiviert.',
    'ui.toggle.daemon_off':      'Daemon deaktiviert.',
    'ui.toggle.idlemind_on':     'IdleMind aktiviert.',
    'ui.toggle.idlemind_off':    'IdleMind deaktiviert.',
    'ui.toggle.selfmod_on':      'Selbst-Modifikation erlaubt.',
    'ui.toggle.selfmod_off':     'Selbst-Modifikation blockiert.',
    'ui.toggle.trust_level':     'Vertrauensstufe: {{level}}.',
    'ui.toggle.auto_resume':     'Auto-Resume offener Ziele: {{mode}}.',
    'ui.toggle.mcp_started':     'MCP-Server gestartet auf Port {{port}}.',
    'ui.toggle.mcp_stopped':     'MCP-Server gestoppt.',
    'ui.toggle.mcp_failed':      'MCP-Server-Toggle fehlgeschlagen: {{error}}',
    'ui.open_in_editor': 'Im Editor öffnen',
    'ui.file_opened': 'Geöffnet: {{file}}',
    'ui.file_imported': 'Importiert: {{file}}',
    'ui.drop_file': 'Datei hier ablegen',
    'ui.undo_success': 'Änderung rückgängig: {{detail}}',
    'ui.undo_failed': 'Undo fehlgeschlagen: {{error}}',
    'ui.undo_nothing': 'Nichts zum Rückgängig machen',
    'ui.goals': 'Ziele',

    'welcome.first': 'Ich bin Genesis. Ich kann meinen eigenen Code verstehen, mich reparieren, neue Fähigkeiten entwickeln und verbesserte Klone von mir erstellen.\n\nSag mir deinen Namen, dann erinnere ich mich beim nächsten Mal an dich.',
    'welcome.returning': 'Hallo {{name}}!',
    'welcome.returning_anon': 'Hey! Schön, dass du wieder da bist. Was steht an?',
    'welcome.returning_familiar': 'Hey! Schön, dass du wieder da bist.',
    'welcome.working_on': 'Woran ich gerade arbeite:',
    'welcome.thoughts': 'Ich hatte bisher {{thoughts}} eigene Gedanken und kenne {{facts}} Fakten.',

    'agent.no_code_block': 'Kein Code-Block gefunden. Benutze ``` um Code einzuschließen.',
    'agent.no_file': 'Keine Datei erkannt. Nenne den Dateinamen mit Endung.',
    'agent.file_not_found': 'Datei "{{file}}" nicht gefunden.',
    'agent.cannot_execute': 'Kann {{ext}} nicht ausführen. Verfügbare Runtimes: {{runtimes}}',
    'agent.shell_unavailable': 'ShellAgent nicht verfügbar.',
    'agent.no_command': 'Kein Befehl erkannt. Schreibe z.B. `$ git status` oder "führe npm test aus".',
    'agent.blocked_command': 'Blockiert: {{reason}}',
    'agent.undo_only_one': 'Nur ein Commit vorhanden — kann nicht rückgängig gemacht werden.',
    'agent.undo_conflict': 'Revert nicht möglich — evtl. Merge-Konflikt. Manuell: `git revert --abort` dann `git reset --hard HEAD~1`.',
    'agent.undo_failed': 'Undo fehlgeschlagen: {{error}}',
    'agent.undo_done': 'Rückgängig gemacht: `{{commit}}`',
    'agent.plan_failed': 'Konnte keinen Plan erstellen.',
    'agent.plan_result': 'Ergebnis: {{ok}} erfolgreich, {{fail}} fehlgeschlagen',
    'agent.no_output': '(keine Ausgabe)',
    'agent.error': 'Fehler',
    'agent.no_test_cmd': 'Kein Test-Befehl für diesen Projekttyp erkannt.',
    'agent.no_install_cmd': 'Kein Install-Befehl für diesen Projekttyp erkannt.',

    'shell.blocked_tier': 'Befehl blockiert auf Tier "{{tier}}": {{cmd}}',
    'shell.permission_unknown': 'Unbekanntes Permission-Level: {{level}}',

    'health.title': 'Genesis — Systemstatus',
    'health.kernel': 'Kernel',
    'health.intact': 'Intakt',
    'health.problem': 'PROBLEM',
    'health.model': 'Modell',
    'health.none': 'keins',
    'health.modules': 'Module',
    'health.skills': 'Skills',
    'health.tools': 'Tools',
    'health.memory': 'Gedächtnis',
    'health.facts': 'Fakten',
    'health.episodes': 'Episoden',
    'health.daemon': 'Daemon',
    'health.cycles': 'Zyklen',
    'health.services': 'Services',
    'health.uptime': 'Uptime',
    'health.shell': 'Shell',
    'health.commands': 'Befehle',

    'project.title': 'Projekt',
    'project.type': 'Typ',
    'project.language': 'Sprache',
    'project.files': 'Dateien',
    'project.git': 'Git',
    'project.unknown': 'unbekannt',
    'project.no_git': 'kein Git',
    'project.commands': 'Verfügbare Befehle',
    'project.dependencies': 'Abhängigkeiten',
    'project.clean': 'sauber',
    'project.changes': '{{n}} Änderungen',

    'tool.file_info': 'Datei-Informationen',
    'tool.execute_file': 'Datei ausführen',
    'tool.knowledge_search': 'Wissensgraph durchsuchen',
    'tool.knowledge_connect': 'Konzepte verbinden',
    'tool.event_query': 'Vergangene Events',
    'tool.web_fetch': 'Eine URL abrufen (Dokumentation, API-Referenz, npm-Pakete)',
    'tool.npm_search': 'npm-Pakete suchen',
    'tool.web_ping': 'Prüfen ob eine URL erreichbar ist',
    'tool.shell_task': 'Plant und führt eine komplexe System-Aufgabe in mehreren Schritten aus (mit Safety-Tiers, Git-Snapshots und Rezept-Lernen)',

    // MCP
    'mcp.connecting': 'Verbinde mit MCP-Server {{name}}...',
    'mcp.connected': 'MCP-Server {{name}} verbunden ({{tools}} Tools)',
    'mcp.disconnected': 'MCP-Server {{name}} getrennt',
    'mcp.error': 'MCP-Fehler ({{name}}): {{error}}',
    'mcp.no_servers': 'Keine MCP-Server konfiguriert',
    'mcp.server_added': 'MCP-Server **{{name}}** hinzugefügt ({{url}})',
    'mcp.server_removed': 'MCP-Server **{{name}}** entfernt',
    'mcp.tools_discovered': '{{count}} Tools von {{name}} entdeckt',
    'mcp.tool_call_failed': 'MCP-Tool-Aufruf fehlgeschlagen: {{error}}',
    'mcp.status_title': 'MCP-Status',
    'mcp.servers': 'Server',
    'mcp.total_tools': 'Tools gesamt',

    'inspect.title': 'Genesis — Selbstbericht',
    'inspect.identity': 'Identität',
    'inspect.modules': 'Module',
    'inspect.files': 'Dateien',
    'inspect.kernel': 'Kernel',
    'inspect.kernel_intact': 'Intakt',
    'inspect.kernel_compromised': 'KOMPROMITTIERT',
    'inspect.capabilities': 'Fähigkeiten',
    'inspect.skills': 'Skills',
    'inspect.none': 'keine',
    'inspect.tools': 'Tools',
    'inspect.tools_registered': 'registriert',
    'inspect.model': 'Modell',
    'inspect.modules_header': 'Module',
    'inspect.protected': 'geschützt',

    'chat.error': 'Fehler: {{message}}',
    'chat.tools_executing': 'Tools ausführen...',
    'chat.no_revertable_commit': 'Kein revertierbarer Commit vorhanden',

    // Shell
    'shell.plan_error': 'Planungsfehler: {{message}}',
    'shell.step_skipped': 'Vorheriger Schritt fehlgeschlagen',

    // Goals
    'goal.no_code': 'Kein Code generiert',
    'goal.file_requested': 'Datei-Erstellung angefordert: {{detail}}',
    'goals.unavailable': 'GoalStack nicht verfügbar.',
    'goals.created': 'Neues Ziel erstellt: **{{description}}**',
    'goals.steps': 'Schritte',
    'goals.empty': 'Noch keine Ziele gesetzt. Sage z.B. "/goal add Bessere Fehlerbehandlung einbauen"',
    'goals.title': 'Ziele',
    'goals.next_step': 'Nächster Schritt',
    // v7.5.0 — slash-discipline + negotiation
    'goals.add_empty': 'Leere Ziel-Beschreibung. Versuche: /goal add <beschreibung>',
    'goals.add_failed': 'Ziel konnte nicht erstellt werden.',
    'goals.cancel_needs_number': 'Welches Ziel? Versuche: /goal cancel <n>  (mit /goal list siehst du die Nummern)',
    'goals.cancel_one_done': '**Ziel abgebrochen:** {{description}}',
    'goals.cancel_one_not_found': '**Ziel #{{idx}} nicht gefunden.** {{count}} aktive Ziele.',
    'goals.cancel_all_confirm': 'Bestätigen: alle {{count}} aktiven Ziele abbrechen? Schicke `/goal clear` nochmal innerhalb von 30 Sekunden zur Bestätigung.',
    'goals.cancel_all_done': '**{{count}} Ziel(e) abgebrochen.**',
    'goals.none_active': '**Keine aktiven Ziele.**',
    'goals.unknown_subcommand': 'Unbekannter Subcommand: `{{sub}}`. Versuche `/goal list`, `/goal add <text>`, `/goal cancel <n>`, `/goal clear`.',
    'goals.help': '**Ziel-Befehle:**\n- `/goal list` — Ziele anzeigen\n- `/goal add <text>` — Ziel hinzufügen\n- `/goal cancel <n>` — Ziel #n abbrechen\n- `/goal clear` — alle abbrechen (fragt nach Bestätigung)\n- `/goal confirm <id>` — vorgeschlagenes Ziel bestätigen\n- `/goal revise <id>: <text>` — Vorschlag überarbeiten\n- `/goal dismiss <id>` — Vorschlag verwerfen',
    'goals.proposed': 'Ziel vorgeschlagen: **"{{description}}"**. Genesis prüft es bevor es aktiv wird.\n\nNutze `/goal confirm {{pendingId}}` zum Annehmen, `/goal revise {{pendingId}}: <neuer text>` zum Überarbeiten, oder `/goal dismiss {{pendingId}}` zum Verwerfen.',
    'goals.confirmed': 'Ziel bestätigt und angelegt: **{{description}}**',
    'goals.revised': 'Vorschlag überarbeitet: **"{{description}}"** (`{{pendingId}}`). Genesis prüft erneut.',
    'goals.dismissed': 'Vorschlag verworfen: {{description}}',
    'goals.pending_id_missing': 'Pending-ID fehlt. Nutze `/goal list` um die Pending-IDs zu sehen.',
    'goals.pending_not_found': 'Vorschlag `{{pendingId}}` nicht gefunden (kann nach 1 Stunde abgelaufen sein).',
    'goals.pending_title': 'Pending (warten auf Bestätigung)',
    'goals.confirm_failed': 'Konnte nicht bestätigen: {{error}}',
    'goals.revise_format': 'Format: `/goal revise <id>: <neue beschreibung>`',
    'goals.negotiation_unavailable': 'Ziel-Verhandlung ist in diesem Build nicht verfügbar.',

    // Peers
    'peer.none_found': 'Keine Peers gefunden.',
    'peer.none_hint': 'Keine Peers. Sage "peer scan" zum Suchen.',
    'peer.found': 'gefunden',

    // Daemon
    'daemon.stopped': 'Daemon gestoppt.',
    'daemon.started': 'Daemon gestartet.',

    // Journal & Plans
    'journal.empty': 'Noch keine Gedanken im Journal.',
    'journal.last': 'letzte {{n}}',
    'plans.empty': 'Noch keine Verbesserungspläne. Ich denke darüber nach wenn ich nicht beschäftigt bin.',
    'plans.title': 'Verbesserungspläne',

    // Settings
    'settings.unavailable': 'Einstellungen nicht verfügbar.',
    'settings.api_key_saved': 'Anthropic API-Key gespeichert ({{key}}...). Neustart für Aktivierung nötig.',
    'settings.not_configured': 'nicht konfiguriert',
    'settings.preferred_model': 'Bevorzugtes Modell',
    'settings.every_n_min': 'alle {{n}} Min',
    'settings.idle_after_min': 'idle nach {{n}} Min',
    'settings.api_key_hint': 'Sage z.B. "Anthropic API-Key: sk-ant-..." um einen Key zu setzen.',

    // Web
    'web.unavailable': 'Web-Zugriff nicht verfügbar.',
    'web.npm_failed': 'npm-Suche fehlgeschlagen: {{error}}',
    'web.npm_no_results': 'Keine Pakete gefunden für: {{query}}',
    'web.fetch_failed': 'Konnte {{url}} nicht abrufen: {{error}}',
    'web.reachable': '**{{url}}** ist erreichbar (Status {{status}})',
    'web.unreachable': '**{{url}}** ist nicht erreichbar: {{error}}',
    'web.hint': 'Gib eine URL an, oder sage z.B. "npm search express" oder "prüfe ob nodejs.org erreichbar ist".',

    // MCP extended
    'mcp.unavailable': 'MCP nicht verfügbar.',
    'mcp.server_not_found': 'Server "{{name}}" nicht gefunden.',
    'mcp.server_started': 'Genesis MCP-Server gestartet auf **Port {{port}}**.\nAndere Agents: `http://127.0.0.1:{{port}}`',
    'mcp.server_start_failed': 'MCP-Server Start fehlgeschlagen: {{error}}',
    'mcp.no_tools_found': 'Keine MCP-Tools gefunden für "{{query}}".',
    'mcp.connect_hint': 'Sage z.B.: `mcp connect github https://mcp.github.com/sse`',

    'selfmod.applied': 'Modifikation angewendet.',
    'selfmod.files': 'Dateien',
    'selfmod.all_intact': 'Alle Systeme intakt.',
    'selfmod.tests_failed': 'Tests fehlgeschlagen:',
    'selfmod.astdiff_applied': 'Präzise Modifikation (ASTDiff) angewendet:',
    'selfmod.warnings': 'Warnungen',
    'selfmod.repair': 'Reparatur',
    'selfmod.greeting': 'Hey! Was kann ich fuer dich tun?',

    // v7.5.7-fix Phase 3 Etappe 2/3: settings UI labels and options
    'ui.on': 'An',
    'ui.off': 'Aus',
    'ui.on_default': 'An (Default)',
    'ui.off_default': 'Aus (Default)',
    'ui.allowed_default': 'Erlaubt (Default)',
    'ui.add': 'Hinzufügen',
    'ui.remove': 'Entfernen',
    'ui.reset_to_default': 'Auf Default zurücksetzen',
    'ui.panel_widths': 'Panel-Breiten',
    'ui.reset_panel_widths': 'Panel-Breiten zurücksetzen',
    'settings.section.layout': 'Layout',
    'settings.layout.panels.hint': 'Setzt Dateibaum, Goals und Editor auf die Standardbreiten zurück. Das Chat-Panel füllt immer den restlichen Platz aus.',

    // Section headers
    'settings.section.cost_guard': 'Kosten-Schutz (Cost-Guard)',
    'settings.section.eventstore_rotation': 'EventStore-Rotation',
    'settings.section.worker_spawner': 'Worker & Spawner',
    'settings.section.memory_extra': 'Memory zusätzlich',
    'settings.section.daemon_behavior': 'Daemon-Verhalten',
    'settings.section.idle_mind': 'IdleMind',
    'settings.section.security': 'Sicherheit',
    'settings.section.health_server': 'Health-Server',
    'settings.section.ui_display': 'UI-Darstellung',
    'settings.section.mcp_external': 'Externe MCP-Server (verbinden)',

    // Field labels
    'settings.cost_guard.enabled': 'Cost-Guard aktiv',
    'settings.cost_guard.session_limit': 'Session-Limit (Tokens)',
    'settings.cost_guard.daily_limit': 'Tages-Limit (Tokens)',
    'settings.cost_guard.warn_threshold': 'Warnung bei (%)',
    'settings.eventstore.size': 'Maximale Dateigröße (MB)',
    'settings.eventstore.rotations': 'Anzahl Rotationen',
    'settings.spawner.timeout': 'SelfSpawner Timeout (Sekunden)',
    'settings.spawner.memory': 'SelfSpawner Memory-Limit (MB)',
    'settings.workerpool.max': 'WorkerPool Threads',
    'settings.episodic.max': 'EpisodicMemory Maximum',
    'settings.idlemind.journal_size': 'IdleMind Journal — Maximale Größe (MB)',
    'settings.idlemind.journal_rotations': 'IdleMind Journal — Anzahl Rotationen',
    'settings.idlemind.max_goals': 'Maximale aktive Goals',
    'settings.daemon.auto_repair': 'Auto-Repair',
    'settings.daemon.auto_optimize': 'Auto-Optimize',
    'settings.security.allow_peers': 'Peer-Network erlauben',
    'settings.security.allow_file_exec': 'File-Execution erlauben',
    'settings.agency.commit_on_shutdown': 'Git-Snapshot bei Shutdown',
    'settings.health.http_enabled': 'HTTP Health-Server',
    'settings.health.http_port': 'HTTP Health-Port',
    'settings.ui.editor_font': 'Editor-Schriftgröße (px)',
    'settings.ui.chat_font': 'Chat-Schriftgröße (px)',
    'settings.openai.models': 'OpenAI Modell-Namen (komma-getrennt)',
    'settings.mcp.list': 'MCP-Server-Liste',
    'settings.mcp.empty': 'Keine MCP-Server konfiguriert.',
    'settings.mcp.placeholder_name': 'Name (z.B. github-mcp)',
    'settings.mcp.placeholder_url': 'URL (https://… oder stdio://…)',
    'settings.validation.out_of_range': 'Wert außerhalb gültigem Bereich. Speichern blockiert.',
    'settings.validation.toast': 'Einige Werte sind außerhalb gültigem Bereich. Bitte korrigieren.',

    // v7.5.7-fix Phase 3 Etappe 6 — final i18n coverage
    'default_hint.label': 'Default',
    'default_hint.min': 'Min',
    'default_hint.max': 'Max',
    'default_hint.on': 'an',
    'default_hint.off': 'aus',
    'default_hint.empty': 'leer',
    'default_hint.not_a_number': 'keine Zahl',
    'settings.validation.out_of_range_with_reason': 'Wert außerhalb gültigem Bereich ({{reason}}). Speichern blockiert.',
    'settings.active_model': 'Aktives Modell',
    'settings.role.chat': 'Chat',
    'settings.role.code': 'Code',
    'settings.role.analysis': 'Analyse',
    'settings.role.creative': 'Kreativ',
    'settings.api_keys': 'API-Keys',
    'settings.keepalive.placeholder': '(Ollama-Default: 5m)',
    'settings.keepalive.hint': 'Wie lange Ollama ein Modell nach dem letzten Call im RAM hält. Beispiele: <code>30s</code>, <code>5m</code>, <code>1h</code>, <code>0</code> (sofort entladen), <code>-1</code> (für immer). Leer = Ollama-Default (5min).',
    'settings.fallback_instructions': 'Klicke <strong>Hinzufügen</strong> um ein Modell in die Kette aufzunehmen. <strong>↑ ↓</strong> zum Umsortieren, <strong>×</strong> zum Entfernen. <span class="cloud-hint">☁ = Cloud (ggf. Abo nötig)</span>',
    // v7.5.7-fix Phase 3 Etappe 7 — JS-generated text i18n
    'settings.mcp.error_name_missing': 'MCP-Server: Name fehlt',
    'settings.mcp.error_url_missing': 'MCP-Server: URL fehlt',
    'settings.mcp.error_exists': 'MCP-Server "{name}" existiert bereits',
    'settings.json.status_loaded': 'geladen',
    'settings.json.status_load_error': 'Fehler beim Laden',
    'settings.json.status_valid': 'JSON gültig',
    'settings.json.status_invalid': 'Ungültig',
    // JSON-Editor (Etappe 4)
    'settings.json.title': 'JSON-Editor (Power-Modus)',
    'settings.json.help': 'Direkter Zugriff auf alle Settings — auch die ~50 nicht in der UI sichtbaren (cognitive Subflags, organism Tuning, peer.discoveryToken, etc.). API-Keys werden hier maskiert angezeigt; setze sie über den Modelle-Tab. Bei ungültigem JSON wird nicht gespeichert.',
    'settings.json.validate': 'Validieren',
    'settings.json.reload': 'Neu laden',

    // v7.5.7-fix Phase 3 Etappe 5 — full i18n coverage (DE)
    'settings.tab.models': 'Modelle',
    'settings.tab.behavior': 'Verhalten',
    'settings.tab.limits': 'Limits',
    'settings.tab.mcp': 'MCP',
    'settings.tab.advanced': 'Erweitert',
    'settings.tab.json': 'JSON-Editor',
    'settings.loading': 'Lädt...',
    'settings.auto_detect': 'Automatisch erkennen',
    'settings.model_roles': 'Modell-Rollen',
    'settings.roles_hint': 'Setzt nur etwas wenn Auto-Routing aktiv ist (siehe Verhalten-Tab).',
    'settings.fallback_chain': 'Fallback-Kette',
    'settings.fallback_help': 'Modelle in Reihenfolge wenn primäres Modell fehlt',
    'settings.fallback_click_to_add': 'Klicke',
    'settings.fallback_to_add': 'zum Hinzufügen',
    'settings.fallback_available': 'Verfügbare Modelle',
    'settings.fallback_your_chain': 'Deine Kette',
    'settings.fallback_empty': 'Keine Fallback-Modelle — Genesis schlägt fehl wenn primäres Modell ausfällt.',
    'settings.anthropic_key': 'Anthropic API-Key',
    'settings.openai_url': 'OpenAI-kompatible API URL',
    'settings.openai_key': 'OpenAI API-Key',
    'settings.openai.models_hint': 'Modelle die als OpenAI-Backend benutzt werden sollen. Leer = Auto-Erkennung (sofern unterstützt). Komma-getrennt.',
    'settings.opt.active': 'Aktiv',
    'settings.opt.off': 'Aus',
    'settings.opt.allowed': 'Erlaubt',
    'settings.opt.blocked_local': 'Blockiert',
    'settings.opt.on': 'An',
    'settings.opt.on_default': 'An (Default)',
    'settings.opt.off_default': 'Aus (Default)',
    'settings.opt.allowed_default': 'Erlaubt (Default)',
    'settings.autoroute.label': 'Auto-Routing für Background-Tasks',
    'settings.autoroute.off': 'Aus — immer Preferred Model nutzen',
    'settings.autoroute.on': 'An — automatisch passendes Modell pro Aufgabe',
    'settings.autoroute.hint': 'Wenn an: Genesis wählt je nach Task-Typ automatisch ein anderes Modell aus deiner Liste. Kann mehrere Modelle parallel im RAM halten.',
    'settings.negotiate.label': 'Goal-Verhandlung vor Hinzufügen',
    'settings.negotiate.off': 'Aus — Goal sofort aktiv',
    'settings.negotiate.on': 'An — erst klären, dann aktivieren',
    'settings.cogstrict.label': 'Cognitive Strict Mode',
    'settings.cogstrict.off': 'Aus — AgentLoop läuft auch ohne alle Cognitive-Services',
    'settings.cogstrict.on': 'An — AgentLoop verlangt verifier/formalPlanner/worldState',
    'settings.section.koennen': 'Können-Konzept (Skill Crystallization)',
    'settings.koennen.enabled.label': 'Können-Pipeline',
    'settings.koennen.enabled.on': 'An (Default) — Affect-Encoding + Crystallization aktiv',
    'settings.koennen.enabled.off': 'Aus — keine Skill-Extraktion aus Trajektorien',
    'settings.koennen.enabled.hint': 'Master-Toggle für das ganze Können-Konzept. Bei aus: KoennenCandidateLog und SkillCrystallizer laufen nicht.',
    'settings.koennen.cryst.enabled.label': 'Skill-Crystallization (Phase 2)',
    'settings.koennen.cryst.enabled.on': 'An (Default) — DreamCycle Phase 3c extrahiert Skills',
    'settings.koennen.cryst.enabled.off': 'Aus — Trajektorien werden geloggt, aber nichts crystallisiert',
    'settings.koennen.cryst.enabled.hint': 'Nur wirksam wenn der Master-Toggle oben an ist. Geht über LLM-Aufrufe — bei limitiertem Token-Budget ggf. ausschalten.',
    'settings.koennen.cryst.minCandidates.label': 'Min. Candidates pro Pattern',
    'settings.koennen.cryst.minCandidates.hint': 'Wie viele ähnliche gate-passed Trajektorien nötig sind, bevor ein Skill extrahiert wird. Default: 3. Höher = konservativer.',
    'settings.koennen.cryst.cooldown.label': 'Pattern-Cooldown (ms)',
    'settings.koennen.cryst.cooldown.hint': 'Wie lange ein fehlgeschlagenes Pattern blockiert ist, bevor es erneut versucht wird. Default: 21600000 ms (= 6 h).',
    'settings.daemon_repair.off': 'Aus — nur erkennen, nicht reparieren',
    'settings.daemon_repair.on': 'An (Default) — repariert erkannte Bugs autonom',
    'settings.daemon_repair.hint': 'Default: an. ImmuneSystem erkennt Probleme; bei aktivem Auto-Repair wird auch repariert. Bei aus: nur Hinweise, keine Aktion.',
    'settings.daemon_optimize.off': 'Aus (Default) — nur Vorschläge, keine Optimierungen',
    'settings.daemon_optimize.on': 'An — wendet vorgeschlagene Optimierungen autonom an',
    'settings.daemon_optimize.hint': 'Default: aus. Daemon schlägt Optimierungen vor; an wendet sie ohne Rückfrage an. Vorsicht — kann Verhalten ändern.',
    'settings.idlemind.max_goals.hint': 'Wie viele Goals IdleMind gleichzeitig verfolgen darf. Default: 3.',
    'settings.security.peers.hint': 'Default: an. Wenn aus: Genesis akzeptiert keine Peer-Verbindungen für Skill/Memory-Austausch.',
    'settings.security.fileexec.hint': 'Default: an. Wenn aus: Genesis darf keine externen Files (Python/Shell) ausführen.',
    'settings.commit_shutdown.off': 'Aus (Default) — kein Auto-Commit',
    'settings.commit_shutdown.on': 'An — committet .genesis/ bei jedem Beenden',
    'settings.commit_shutdown.hint': 'Default: aus (v7.5.7-fix Phase 3). Auf einem geteilten Repo: aus lassen, sonst landen Genesis-Files in deiner Git-History.',
    'settings.agency.git_auto_init': 'Git-Repo automatisch initialisieren',
    'settings.git_auto_init.off': 'Aus (Default) — kein "git init"',
    'settings.git_auto_init.on': 'An — "git init" wenn kein Repo vorhanden',
    'settings.git_auto_init.hint': 'Default: aus (v7.7.1-hotfix). Genesis erstellt kein .git-Verzeichnis ohne deine Zustimmung. Dein bestehendes Repo wird nie angefasst.',
    'settings.agency.git_auto_commit': 'Git-Auto-Commit bei Selbst-Modifikation',
    'settings.git_auto_commit.off': 'Aus (Default) — keine automatischen Commits',
    'settings.git_auto_commit.on': 'An — Genesis committet vor/nach Selbst-Modifikationen',
    'settings.git_auto_commit.hint': 'Default: aus (v7.7.1-hotfix). SnapshotManager und GenesisBackup sind die aktiven Fallback-Layer und decken denselben Use Case ab, ohne deine Git-History anzufassen.',
    // v7.5.9 ZIP6 — Software-Installation Einstellungen.
    'settings.section.install': 'Software-Installation (v7.5.9 ZIP 5)',
    'settings.install.allow_auto.label': 'Auto-Install via Package-Manager (Tier 1+2)',
    'settings.install.allow_auto.off': 'Aus (Default) — nur Vorschau anzeigen',
    'settings.install.allow_auto.on': 'An — winget/choco/brew/apt automatisch ausführen, plus Bootstrap wenn PM fehlt',
    'settings.install.allow_auto.hint': 'Wenn an + Trust ≥ AUTONOMOUS: Genesis installiert via Package-Manager ohne Bestätigung. Wenn der PM fehlt, versucht Genesis ihn einzurichten. Default: aus.',
    'settings.install.full_autonomy.label': 'Volle Install-Autonomie (Tier 3 — Direct Download)',
    'settings.install.full_autonomy.off': 'Aus (Default) — kein automatischer Download',
    'settings.install.full_autonomy.on': 'An — Genesis lädt Installer von offiziellen Vendor-URLs und startet sie',
    'settings.install.full_autonomy.hint': 'Nur wirksam wenn "Auto-Install" auch an. Wenn an: bei "installiere X" lädt Genesis Files (winrar, vscode, firefox, chrome, git, python, nodejs, vlc, 7zip, notepad++) nach Downloads und startet den Installer. Du musst nur den Windows-UAC-Dialog klicken — der ist nicht automatisierbar. Default: aus.',
    'settings.install.scope.label': 'Install-Ziel (winget --scope)',
    'settings.install.scope.machine': 'Machine — system-weit in C:\\Program Files\\ (Default, Admin-Prompt)',
    'settings.install.scope.user': 'User — pro Benutzer in AppData\\ (kein Admin nötig)',
    'settings.install.scope.auto': 'Auto — winget entscheidet (manche Pakete ignorieren --scope)',
    'settings.install.scope.hint': 'Bestimmt wo winget Software ablegt. "Machine" erzeugt einen Admin-Prompt aber landet in Program Files. "User" ist Admin-frei aber landet in AppData (manchmal nur als .lnk). Manche Pakete (wie WinRAR) ignorieren --scope und installieren immer im selben Bereich. Per-Aufruf überschreibbar mit /install <name> <pfad> (z.B. /install winrar D:\\Programme\\WinRAR).',
    'settings.section.memory_caps': 'Memory-Caps',
    'settings.section.timeouts': 'Timeouts',
    'settings.maxconcurrent.label': 'Maximum gleichzeitige LLM-Anfragen',
    'settings.maxconcurrent.hint': 'Wie viele LLM-Anfragen gleichzeitig laufen dürfen. Hoch = mehr Parallelität, kann auf CPU thrashing verursachen. Default: 3.',
    'settings.maxworkers.label': 'Maximum parallele Worker-Prozesse',
    'settings.maxworkers.hint': 'Wie viele Worker-Subprozesse SelfSpawner gleichzeitig forken darf. Default: 3.',
    'settings.keepalive.label': 'Ollama Keep-Alive',
    'settings.kg.label': 'KnowledgeGraph Maximum (Nodes)',
    'settings.kg.hint': 'Maximale Anzahl Knoten im Wissens-Graph. Bei Überschreitung wird der älteste/seltenste entfernt. 0 = unbegrenzt.',
    'settings.sslog.label': 'SelfStatementLog Maximum',
    'settings.sslog.hint': 'Maximale Anzahl Self-Statements gesamt. Bei Überschreitung werden alte gepruned. 0 = unbegrenzt.',
    'settings.approval_timeout.label': 'Approval Timeout (Sekunden)',
    'settings.approval_timeout.hint': 'Wie lange Genesis auf eine Approval-Antwort wartet bevor es abbricht.',
    'settings.cost_guard.enabled.hint': 'Schützt vor unbegrenzten LLM-Kosten durch IdleMind/DreamCycle/Daemon. User-Chat wird nie blockiert, nur autonome Calls. Default: an.',
    'settings.cost_guard.session.hint': 'Token-Budget pro Session. Default: 500.000.',
    'settings.cost_guard.daily.hint': 'Token-Budget pro Tag (Reset um Mitternacht). Default: 2.000.000.',
    'settings.cost_guard.warn.hint': 'Bei welchem Prozentsatz des Limits gewarnt wird. Default: 80.',
    'settings.eventstore.size.hint': 'Bei Überschreitung wird events.jsonl rotiert (.1, .2, ...). 0 = keine Rotation. Default: 50.',
    'settings.eventstore.rot.hint': 'Wie viele rotierte Files behalten werden. 0 = keine. Default: 3.',
    'settings.spawner.timeout.hint': 'Maximale Laufzeit eines Worker-Prozesses bevor er gekillt wird. Default: 300s (5 min).',
    'settings.spawner.memory.hint': 'Maximaler RAM pro Worker-Prozess. Default: 256 MB.',
    'settings.workerpool.hint': 'Anzahl Worker-Threads für GenericWorker (Code-Analyse etc.). 0 = automatisch (CPU-Cores − 1). Default: 0.',
    'settings.episodic.hint': 'Maximale Anzahl gespeicherter Episodes. 0 = unbegrenzt. Default: 500.',
    'settings.idlemind.journal_size.hint': 'Bei Überschreitung wird IdleMind-Journal rotiert. Default: 10.',
    'settings.idlemind.journal_rot.hint': 'Wie viele rotierte Journal-Files behalten werden. Default: 3.',
    'settings.mcp.serve.label': 'MCP Server (Genesis bereitstellen)',
    'settings.mcp.port.label': 'MCP Server Port',
    'settings.mcp.list_hint': 'Externe MCP-Server zum Verbinden. Genesis ruft deren Tools über mcp-call auf. Änderungen werden beim Speichern übernommen.',
    'settings.cogsim.branches': 'Cognitive Simulation — Max Branches',
    'settings.cogsim.depth': 'Cognitive Simulation — Max Depth',
    'settings.emotion.decay.label': 'Emotion Decay-Intervall (Sekunden)',
    'settings.emotion.decay.hint': 'Wie oft Emotionen Richtung Baseline driften. Default 60s. Niedriger = schneller Beruhigung, höher = stabilere Stimmungen.',
    'settings.loneliness.label': 'Loneliness-Wachstums-Intervall (Sekunden)',
    'settings.loneliness.hint': 'Wie oft Loneliness passiv wächst wenn keine Interaktion. Default 300s (5min).',
    'settings.idlemind.idle': 'IdleMind — Idle-Schwelle (Minuten)',
    'settings.idlemind.think': 'IdleMind — Think-Intervall (Minuten)',
    'settings.daemon.cycle': 'Daemon — Cycle (Minuten)',
    'settings.health.http.hint': 'Default: aus. Wenn an: Genesis stellt /health, /metrics, /events HTTP-Endpoints für externes Monitoring bereit.',
    'settings.health.port.hint': 'Port für den Health-Server. Default: 9090.',
    'settings.ui.editor_font.hint': 'Schriftgröße im Code-Editor. Default: 13.',
    'settings.ui.chat_font.hint': 'Schriftgröße im Chat-Bereich. Default: 13.',
    // v7.9.4: Können Phase 3
    'settings.koennen_acquisition_context_enabled': 'Biographie für neue Fähigkeiten erzeugen',
    'settings.koennen_acquisition_context_help': 'Wenn eine Fähigkeit kristallisiert wird, schreibt Genesis einen Satz darüber was ohne sie gefehlt hätte. Ein kleiner LLM-Aufruf pro Kristallisation.',
    'settings.koennen_rehearsal_enabled': 'Ausstehende Fähigkeiten im Idle üben',
    'settings.koennen_rehearsal_help': 'Im Leerlauf wählt Genesis eine ausstehende Fähigkeit und führt sie mit einem generierten Input aus um Wirksamkeits-Daten zu sammeln.',
    'settings.koennen_promotion_enabled': 'Genesis darf eigene Fähigkeiten befördern',
    'settings.koennen_promotion_help': 'Wenn eine Fähigkeit alle vier Reife-Kriterien erfüllt befördert Genesis sie aus dem ausstehenden Zustand in produktive Nutzung.',
    'settings.koennen_promotion_min_invocations': 'Mindest-Übungen vor Beförderung',
    'settings.koennen_promotion_min_wilson_lb': 'Mindest-Wilson-LB',
    'settings.koennen_promotion_min_distinct_inputs': 'Mindest-Anzahl unterschiedlicher Übungs-Inputs',
    'settings.koennen_promotion_min_age_hours': 'Mindest-Alter in Stunden',
    'koennen.toast_promoted': 'Fähigkeit erworben: {{name}}',
    'koennen.toast_discarded': 'Fähigkeit losgelassen: {{name}}',
    'koennen.toast_quarantined': 'Fähigkeit unter Quarantäne: {{name}}',
    'koennen.toast_discard_suggested': 'Erwäge loszulassen: {{name}}',
    'koennen.no_biography': 'Keine Biographie (kristallisiert vor v7.9.4)',
    'koennen.status_promoted': 'Befördert',
    'koennen.status_rehearsing': 'Übend',
    'koennen.status_pending': 'Ausstehend',
    'koennen.status_quarantined': 'Quarantäne',
    'koennen.status_discarded': 'Losgelassen',
  },
  fr: {
    'ui.booting': 'Démarrage...',
    'ui.ready': 'Prêt',
    'ui.error': 'Erreur',
    'ui.placeholder': 'Message à Genesis...',
    'ui.settings': 'Paramètres',
    'ui.undo': 'Annuler',
    'ui.still_starting': 'Genesis démarre encore...',
    'ui.settings_saved': 'Paramètres enregistrés',
    'ui.cancel': 'Annuler',

    'welcome.first': "Je suis Genesis. Je peux comprendre mon propre code source, me réparer, développer de nouvelles capacités et créer des clones améliorés.\n\nDis-moi ton nom et je m'en souviendrai la prochaine fois.",
    'welcome.returning': 'Bonjour {{name}} !',
    'welcome.returning_anon': 'Salut ! Content de te revoir. Quoi de neuf ?',
    'welcome.returning_familiar': 'Salut ! Content de te revoir.',

    'agent.error': 'Erreur',
    'agent.no_output': '(aucune sortie)',

    'inspect.title': 'Genesis — Auto-rapport',
    'inspect.kernel_intact': 'Intact',
    'inspect.kernel_compromised': 'COMPROMIS',
    'chat.error': 'Erreur: {{message}}',
    'chat.tools_executing': 'Exécution des outils...',
    'chat.no_revertable_commit': 'Aucun commit réversible disponible',
  },

  es: {
    'ui.booting': 'Iniciando...',
    'ui.ready': 'Listo',
    'ui.error': 'Error',
    'ui.placeholder': 'Mensaje a Genesis...',
    'ui.settings': 'Configuración',
    'ui.undo': 'Deshacer',
    'ui.still_starting': 'Genesis aún está iniciando...',
    'ui.settings_saved': 'Configuración guardada',
    'ui.cancel': 'Cancelar',

    'welcome.first': 'Soy Genesis. Puedo entender mi propio código fuente, repararme, desarrollar nuevas capacidades y crear clones mejorados.\n\nDime tu nombre y te recordaré la próxima vez.',
    'welcome.returning': '¡Hola {{name}}!',
    'welcome.returning_anon': '¡Hola! Me alegra verte de nuevo. ¿Qué hay?',
    'welcome.returning_familiar': '¡Hola! Me alegra verte de nuevo.',

    'agent.error': 'Error',
    'agent.no_output': '(sin salida)',

    'inspect.title': 'Genesis — Autoinforme',
    'inspect.kernel_intact': 'Intacto',
    'inspect.kernel_compromised': 'COMPROMETIDO',
    'chat.error': 'Error: {{message}}',
    'chat.tools_executing': 'Ejecutando herramientas...',
    'chat.no_revertable_commit': 'No hay commit reversible disponible',
  },
};

// Singleton
const lang = new Language();

module.exports = { Language, lang, STRINGS };
